### ISSUE TITLE
"ld: cannot find -lcuda_runtime" when building AMReX code with Ascent

### ISSUE THREAD

**Issue by BenWibking** [Alpine-DAV/ascent#1014]
I am getting a strange link error when I build my AMReX code with CUDA enabled and Ascent+Conduit enabled. When `AMReX_ASCENT` is off, it builds and runs fine.

```
[ 97%] Linking CXX executable test_hydro3d_blast
/usr/bin/ld: cannot find -lcuda_runtime
collect2: error: ld returned 1 exit status
make[3]: *** [src/HydroBlast3D/CMakeFiles/test_hydro3d_blast.dir/build.make:225: src/HydroBlast3D/test_hydro3d_blast] Error 1
make[2]: *** [CMakeFiles/Makefile2:1847: src/HydroBlast3D/CMakeFiles/test_hydro3d_blast.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1854: src/HydroBlast3D/CMakeFiles/test_hydro3d_blast.dir/rule] Error 2
make: *** [Makefile:634: test_hydro3d_blast] Error 2
```

If this is an AMReX issue instead, I can move it there.

**Comment by BenWibking** [comment]
I've built Ascent on this system with the CUDA build script (https://github.com/Alpine-DAV/ascent/blob/develop/scripts/build_ascent/build_ascent_cuda.sh) with no modifications.

**Comment by cyrush** [comment]
This is an Ascent issue -- can you share:

`make VERBOSE=1`

**Comment by BenWibking** [comment]
Sure, here's the full log: 
[build_log.txt](https://github.com/Alpine-DAV/ascent/files/9560194/build_log.txt)

**Comment by cyrush** [comment]
Ok - I think this is coming from the camp library.  They have a new release that I think addresses this issue.  I'll try to update the build script and test soon.

**Comment by cyrush** [comment]
@BenWibking  https://github.com/Alpine-DAV/ascent/pull/1019 should resolve this problem.

I haven't fully tested with CUDA yet, but I plan to tomorrow.

**Comment by BenWibking** [comment]
Ok, I've rebuilt Ascent and my code links successfully.

It crashes at runtime, though, because my code's CMake build picks up a different HDF5 than used by Ascent, and the first call to HDF5 detects a header/library mismatch. I haven't seen this happen before, but this is on a new cluster so I'm not sure if it's an Ascent issue or something else.

**Comment by BenWibking** [comment]
Ok, I was able to fix it. It works now.

**Comment by cyrush** [comment]
thanks for follow up info!
