### ISSUE TITLE
disable session YAML file

### ISSUE THREAD

**Issue by ibaned** [Alpine-DAV/ascent#1020]
Hi, is there any way to disable the outputting of the `ascent_session.yaml` file? As a user who wants to keep the output directory clean, I would like to opt out of this logging mechanism.

Thank you!

**Comment by cyrush** [comment]
@ibaned yes you can disable this.

In the options passed to `Ascent::open()`, set the session name to an empty string:

```
session_name: ""
```

C++ Example:

```
Node opts;
opts["session_name"] = "";
ascent.open(opts);
```

Let me know if you have any issues with this.

I want to keep this ticket open as a reminder to add this info to our docs. 

Also, if they do want to save out the session details explicitly @develop of Ascent has a `save_session` action they can use. 

https://ascent.readthedocs.io/en/latest/Actions/ExpressionsOverview.html?highlight=session#save-session-action

**Comment by ibaned** [comment]
Thank you, I can confirm that this works!
