### ISSUE TITLE
remove #warning from source code

### ISSUE THREAD

**Issue by ibaned** [Alpine-DAV/ascent#1021]
Hello,

There is a preprocessor warning line in the source code:
```
ascent/runtimes/ascent_expression_eval.cpp:1554:  #warning "Need a way to delete the intermediate results during execution"
```

Could this please be removed so it doesn't cause warnings in all user builds?

It seems like it is essentially a "TODO" note for the developers, should it perhaps be converted to an issue in an issue tracker?

Thank you!

**Comment by cyrush** [comment]
Good suggestion, we will change these to tickets.
