### ISSUE TITLE
Plotting the log of a field

### ISSUE THREAD

**Issue by ibaned** [Alpine-DAV/ascent#1025]
Hello,

Is there a way to use a logarithmic scale when plotting a field? I even looked at using a pipeline expression filter but I don't think the logarithm is a supported function on fields.

Many thanks!
Dan

**Comment by nicolemarsaglia** [comment]
A potential solution is to apply a logarithmic filter to a field and then render the output: https://ascent.readthedocs.io/en/latest/Actions/Examples.html?highlight=log10#an-example-of-using-the-log10-filter

There are 3 different log filter variations:  "log" is for natural log, "log10" for log base 10, and "log2" is for log base 2. 

Is this what you're looking for?

**Comment by ibaned** [comment]
This seems to work, thank you!
