### ISSUE TITLE
Verify VTK-m Compilation Options

### ISSUE THREAD

**Issue by FreddieWitherden** [Alpine-DAV/ascent#1065]
When trying to compile Ascent by hand I encountered a double-to-float type error related to VTK-m.  After much digging I found that Ascent requires VTK-m to be compiled with `-DVTKm_USE_DOUBLE_PRECISION=ON` but does not verify that this is indeed the case in the configuration step.

To this end it would be good if the Ascent CMakeLists.txt verified that the provided VTK-m install has been configured correctly.  This would avoid some rather hard to debug error messages further down in the build process.

**Comment by nicolemarsaglia** [comment]
Apologies for the time spent debugging this, but thank you for pointing this out. You're correct, there should be a CMake check, as well as clearer documentation regarding necessary VTKm flags. We will get on this.

**Comment by nicolemarsaglia** [comment]
A check is added in #1067 . This is waiting on a VTKm merge that makes the necessary flag visible. That was why there was not check in the first place.

**Comment by cyrush** [comment]
#1067 will resolve this. 

We planned to include this for 0.9.2, now that we are using VTK-m 2.0, however it turns out the CMake logic isn't fully there yet. So we will need to wait for a new VTK-m patch release and address after 0.9.2

**Comment by cyrush** [comment]
resolved in #1067 and with Ascent develop updated to support VTK-m 2.1.0
