### ISSUE TITLE
build fails with CUDA 12 due to VTK-m issue

### ISSUE THREAD

**Issue by BenWibking** [Alpine-DAV/ascent#1083]
The VTKm build fails when using CUDA 12. This is the upstream issue in the VTK-m bug tracker: https://gitlab.kitware.com/vtk/vtk-m/-/issues/751.

**Comment by cyrush** [comment]
thanks for the info, we will also ask vtk-m folks about progress

**Comment by cyrush** [comment]
Resolved for 0.9.2.

We are using vtk-m 2.0 and I have CI tests against CUDA 12.1.1.

Let us know if you encounter new challenges.
