### ISSUE TITLE
When OpenMPI is chosen binaries are still linked with mpich

### ISSUE THREAD

**Issue by yurivict** [Alpine-DAV/ascent#1091]
When ```ENABLE_MPI=ON``` is set and ```MPI_HOME=/usr/local/mpi/openmpi``` is set, and compilers are set accordingly binaries are still linked with mpich.

Version: 0.9.0
clang-14
FreeBSD 13.1

**Comment by cyrush** [comment]
@yurivict In this case, are there mpi compiler wrappers in the path when compiled?

I am not sure the CMake precedence of other options vs `MPI_HOME`.

We usually explicitly set:

```
-DENABLE_MPI=ON
-DMPI_C_COMPILER=...
-DMPI_CXX_COMPILER=...
```

**Comment by cyrush** [comment]
Resolving, using the specific CMake MPI compiler wrapper vars does allow you to select a specific mpi. (We test this in our spack builds)
