### ISSUE TITLE
Request for more helpful color map error message

### ISSUE THREAD

**Issue by slabasan** [Alpine-DAV/ascent#11]
I ran into this error with the `color_map` settings in `alpine_actions.json` (copied below). It was looking for `"type": "alpha"`, but I had `"type": "Alpha"`. It would be helpful if the error message was formatted like the desired format (i.e., with quotation marks) in the actions file or if the error message printed out what the valid options are.

```
terminate called after throwing an instance of 'conduit::Error'
  what():  
{
  "file": "/usr/workspace/wsa/labasan1/quartzdat/alpine-generate-perf-model-data/src/alpine/pipelines/alpine_vtkm_renderer.cpp",
  "line": 756,
  "message": "Unknown control point type Alpha"
}
```

**Comment by mclarsen** [comment]
This is resolved with #39
