### ISSUE TITLE
render failure with slice filter (but only on GPU)

### ISSUE THREAD

**Issue by BenWibking** [Alpine-DAV/ascent#1119]
We (@pgrete and I) are seeing a render failure with the slice filter for GPU runs with our Parthenon-based code. It renders fine on GPU without the slice filter, and it always works on host runs. The simulation snapshots on disk are identical whether running on host or GPU.

I haven't seen this issue with my AMReX code, but I haven't run that with the latest (0.9.0) version of Ascent, so I am wondering if this is a recently introduced bug.

A reproducer is here: https://github.com/parthenon-hpc-lab/athenapk/pull/41.

Failure (on GPU run):
![dens00252](https://user-images.githubusercontent.com/1781919/226694155-7c7dbf46-5a02-43ac-b10f-4d79e516c780.png)

Success (on host only run):
![dens00252](https://user-images.githubusercontent.com/1781919/226694095-9636b990-77b4-46e8-a2a1-a0d2ae7f6a4e.png)

**Comment by cyrush** [comment]
@BenWibking is this right on the edge of the mesh?

We have seen numerics differences between GPU and non GPU in cases with slices in cases like that that lead to similar issues. 

Thanks for the reproducer, we can try to track this down.

**Comment by BenWibking** [comment]
It should be precisely cut through the center of the mesh. Since it's an octree mesh, the individual mesh blocks should be on either side of the plane without intersecting any interior volume, which might explain what's going on.

**Comment by BenWibking** [comment]
Closing as duplicate.
