### ISSUE TITLE
Build errors when upgrading to VTKm 2.0.0 

### ISSUE THREAD

**Issue by WillTrojak** [Alpine-DAV/ascent#1136]
I recently updated to VTKm 2.0.0 adn I'm struggling to get ascent to compile. First when making ascent, it wasn't able to find some of the vtk-m headers. I fixed this by manually handing some more paths to my CFLAGS. The second issue is that ld can't find the various vtkm library .so files.

This might just be an issue on my side, but it looks like the vtkm library so file names might have changed. Any help would be great.

Below is the error given from `make -j1`:
```
$ make -j1
...
[  4%] Linking CXX shared library ../../../lib/libvtkh_utils.so
/usr/bin/ld: cannot find -lvtkm_cont
/usr/bin/ld: cannot find -lvtkm_filter
/usr/bin/ld: cannot find -lvtkm_rendering
collect2: error: ld returned 1 exit status
make[2]: *** [libs/vtkh/utils/CMakeFiles/vtkh_utils.dir/build.make:123: lib/libvtkh_utils.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:930: libs/vtkh/utils/CMakeFiles/vtkh_utils.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by cyrush** [comment]
Hi Will,
VTK-m 2.0 has API changes that make it incompatible with ascent 0.9.0 and 0.9.1. (They removed deprecated apis as part of a major release) .We  are working on Ascent 0.9.2 which support the changes for VTK-m 2.0.

-Cyrus
________________________________
From: Will Trojak ***@***.***>
Sent: Monday, April 24, 2023 3:37 AM
To: Alpine-DAV/ascent ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Alpine-DAV/ascent] Build errors when upgrading to VTKm 2.0.0 (Issue #1136)


I recently updated to VTKm 2.0.0 adn I'm struggling to get ascent to compile. First when making ascent, it wasn't able to find some of the vtk-m headers. I fixed this by manually handing some more paths to my CFLAGS. The second issue is that ld can't find the various vtkm library .so files.

This might just be an issue on my side, but it looks like the vtkm library so file names might have changed. Any help would be great.

Below is the error given from make -j1:

$ make -j1
...
[  4%] Linking CXX shared library ../../../lib/libvtkh_utils.so
/usr/bin/ld: cannot find -lvtkm_cont
/usr/bin/ld: cannot find -lvtkm_filter
/usr/bin/ld: cannot find -lvtkm_rendering
collect2: error: ld returned 1 exit status
make[2]: *** [libs/vtkh/utils/CMakeFiles/vtkh_utils.dir/build.make:123: lib/libvtkh_utils.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:930: libs/vtkh/utils/CMakeFiles/vtkh_utils.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by WillTrojak** [comment]
Ah ok, I'll revert to 1.9.0 and wait until you've got support for v2. Thanks!
