### ISSUE TITLE
Default actions in CloverLeaf

### ISSUE THREAD

**Issue by slabasan** [Alpine-DAV/ascent#114]
Currently, default actions exist in CloverLeaf source, as shown below: 

```
!CALL conduit_node_set_path_char8_str(add_scene_act,"action", "add_scenes")

!scenes = conduit_node_fetch(add_scene_act,"scenes")
!CALL conduit_node_set_path_char8_str(scenes,"s1/plots/p1/type", "volume")
!CALL conduit_node_set_path_char8_str(scenes,"s1/plots/p1/params/field", "energy")
```

Resetting the actions at the top of the `ascent_actions.json` file does not remove the defaults.

**Comment by mclarsen** [comment]
We have now changed the behavior so that if the user provides an ascent_actions file, then ascent's actions are completely replaced with the contents of the actions file.
