### ISSUE TITLE
databinning vorticity causes warning "Field type unsupported for conversion to blueprint"

### ISSUE THREAD

**Issue by BenWibking** [Alpine-DAV/ascent#1146]
We have a pipeline that applies the vorticity filter to the velocity field -> vector magnitude filter -> DataBinning with a scalar field axis. This appears to produce correct output, but it causes the a warning message similar to the following for each domain in the mesh:

```
 Skipping.Field type unsupported for conversion to blueprint.
   gradient assoc= Points valueType=vtkm::Vec<vtkm::Vec<double, 3>, 3> storageType=vtkm::cont::StorageTagBasic 15625 values occupying 1125000 bytes [((1.11588e-169,4.39685e-152,-2.65875e-180),(-2.47755e-165,2.03444e-153,1.78584e-175),(1.11598e-169,-1.03699e-153,-2.65879e-180)) ((1.11588e-169,4.46591e-152,-2.65877e-180),(-1.23877e-165,1.01732e-153,8.92925e-176),(5.57991e-170,1.55873e-154,-1.32941e-180)) ((5.57941e-170,2.33658e-152,-1.32941e-180),(-1.70865e-171,1.04028e-157,5.33424e-181),(2.01823e-176,6.74664e-154,-1.79718e-185)) ... ((-1.0925e-286,-3.55353e-187,0),(1.05288e-302,-6.90374e-192,0),(1.05293e-302,1.00726e-189,0)) ((-1.05293e-302,-9.958e-190,0),(0,-2.26873e-194,0),(0,7.45482e-193,0)) ((0,-1.5415e-192,0),(0,-1.7697e-194,0),(0,-3.4684e-194,0))]
```

A full reproducer is here: https://github.com/parthenon-hpc-lab/athenapk/pull/64.

**Comment by cyrush** [comment]
@BenWibking 

Thanks for the report -- This issue should be resolved in https://github.com/Alpine-DAV/ascent/pull/1138, which was merged to develop.

Note: We are now using VTK-m 2.0 for develop and are close to an Ascent 0.9.2 release, which will support VTK-m 2.0.

For your current runs, you can ignore the error.  The error is that it is skipping conversion of the intermediate u,v,w gradient data that was used to calculate the vorticity.

The fix in the PR removes the intermediate gradient results  - which also free some memory that isn't needed after we have the vorticity.

**Comment by BenWibking** [comment]
Thanks, it's good to know we can still run with it for now. We'll install 0.9.2 as soon as it's released.

**Comment by BenWibking** [comment]
Confirmed fixed via https://github.com/Alpine-DAV/ascent/pull/1138.
