### ISSUE TITLE
Colorbar possition in pseudocolor

### ISSUE THREAD

**Issue by WillTrojak** [Alpine-DAV/ascent#1151]
In ascent, I couldn't find an option for changing the position/size of the colorbar in pseudocolor-type scenes, is this possible or would this be something that could be added?

**Comment by nicolemarsaglia** [comment]
@WillTrojak Correct. I think the extent of our color bar control is On/Off for visibility. 

But I believe it is something that can be added! I can get started on this tomorrow. 

If there is immediate need I can poke around and find out where it can be hard coded within Ascent?

**Comment by WillTrojak** [comment]
Thanks, I think it would be a really handy addition. We have some time coming up on Frontier and we want to show off the ascent functionality in PyFR so it would be great if there was some way to move the color bars so we can produce camera-ready images as we go.

**Comment by nicolemarsaglia** [comment]
Addressing this in PR #1152 

It shouldn't take me more than a couple of days, but Cyrus is off next week and I typically don't like to merge into the develop branch without getting his eyes on everything first. 

If you need a hacky solution sooner, here is where you can change the position of the color bar in Ascent: https://github.com/Alpine-DAV/ascent/blob/e7e39e0c8fcd7a7a203688b5f16b5720af546016/src/libs/vtkh/rendering/Annotator.cpp#L16

You can change the position using the bounds of p1. p2-p4 are if you have more than one color bar (we only support up to 4). 

Zooming out from your data is also an option if things aren't fitting how you want: https://ascent.readthedocs.io/en/latest/Actions/Examples.html?highlight=zoom#an-example-of-creating-a-render-specifying-all-camera-parameters

**Comment by nicolemarsaglia** [comment]
For reference of how the positions change. Here is p1 (default): 
![energy_default_colorbar](https://github.com/Alpine-DAV/ascent/assets/24232495/d910acef-7eed-4039-a59e-071f48bc5371)

p2: 
![energy_new_colorbar2](https://github.com/Alpine-DAV/ascent/assets/24232495/3d7a2dd4-aea0-4f7a-b33e-9a8ff5a66174)

p3: 
![energy_new_colorbar3](https://github.com/Alpine-DAV/ascent/assets/24232495/5435d79a-05d4-4ff0-a34d-8623f970eb15)

p4:
![energy_new_colorbar4](https://github.com/Alpine-DAV/ascent/assets/24232495/7dcf7d7d-394e-438e-9f49-073024a23561)

**Comment by WillTrojak** [comment]
That's fantastic, thanks!

**Comment by nicolemarsaglia** [comment]
Resolved in #1152
