### ISSUE TITLE
Will the Spack package have OCCA variant again?

### ISSUE THREAD

**Issue by yzhu-ub** [Alpine-DAV/ascent#1153]
I searched through issues but found no related info yet -- I noticed that the Spack package doesn't have OCCA variant anymore (it was there in v0.8.0, was it?)

Will it be back? Or, for what reason did you decide to remove this variant?

**Comment by nicolemarsaglia** [comment]
@cyrush should have more information on this. But unfortunately he is out this week. I'll do some digging to see if I can find an answer in the meantime, I will let you know if I come up anything.

**Comment by cyrush** [comment]
@yzhu-ub  are you using spack develop?

I don't know if we ever got the occa package dependency into spack develop, but it exists in our spack custom packages that we use for our CI:

https://github.com/Alpine-DAV/ascent/blob/8609488d1a06b7f1ac049b4043030da6e01899ee/scripts/uberenv_configs/packages/ascent/package.py#L91

I can add it to spack develop if that is needed.

**Comment by yzhu-ub** [comment]
@cyrush I suppose that by "spack develop" you meant the develop branch of Spack official repo, is it correct? It would be nice to have the OCCA variant there.

I'm using Spack currently with release v0.20.0, but I can switch to develop nonetheless.

**Comment by cyrush** [comment]
Yes --  sorry for the jargon, I did mean the develop branch of offical spack repo.

I'll work to get occa added to the package.

**Comment by cyrush** [comment]
Working on this via this spack PR:
https://github.com/spack/spack/pull/38426

**Comment by cyrush** [comment]
resolving, we were able to add the occa variant back to spack in https://github.com/spack/spack/pull/38426
