### ISSUE TITLE
host-only build on Frontier fails with "clang-15: error: unknown argument: '-fcompare-debug-second'"

### ISSUE THREAD

**Issue by BenWibking** [Alpine-DAV/ascent#1163]
We need a host-only build on Frontier to work around issue https://github.com/Alpine-DAV/ascent/issues/1119.

On Frontier, I loaded
```
module load PrgEnv-cray cce/15.0.1 cmake cray-python cray-mpich/8.1.23
```
and tried to build a host-only version of Ascent with
```
env enable_tests=OFF enable_mpi=ON enable_find_mpi=OFF ./build_ascent.sh
```
This successfully built all of the dependencies but the Ascent build failed with compiler errors:
```
[ 12%] Built target vtkh_utils_mpi
gmake[2]: *** [libs/dray/CMakeFiles/dray_mpi.dir/build.make:107: libs/dray/CMakeFiles/dray_mpi.dir/array_internals.cpp.o] Error 1
gmake[2]: *** [libs/dray/CMakeFiles/dray_mpi.dir/build.make:93: libs/dray/CMakeFiles/dray_mpi.dir/array.cpp.o] Error 1
clang-15: error: unknown argument: '-fcompare-debug-second'
gmake[2]: *** [libs/dray/CMakeFiles/dray_mpi.dir/build.make:121: libs/dray/CMakeFiles/dray_mpi.dir/array_internals_base.cpp.o] Error 1
gmake[2]: Leaving directory '/lustre/orion/ast146/proj-shared/ascent_cpu/build/ascent-develop'
gmake[1]: *** [CMakeFiles/Makefile2:1037: libs/dray/CMakeFiles/dray_mpi.dir/all] Error 2
gmake[1]: Leaving directory '/lustre/orion/ast146/proj-shared/ascent_cpu/build/ascent-develop'
gmake: *** [Makefile:139: all] Error 2
```

The full build log is here:  [frontier_cpu_build_log.txt](https://github.com/Alpine-DAV/ascent/files/11884621/frontier_cpu_build_log.txt)

**Comment by nicolemarsaglia** [comment]
Interesting... Thanks for posting this! I will try getting a successful host-only build on Frontier and let you know!

**Comment by nicolemarsaglia** [comment]
I found success with the following recipe: 
```
module load cmake 
module load PrgEnv-cray
module load cray-mpich/8.1.23
module load cce/15.0.1
module load cray-python

export CC=$(which cc)
export CXX=$(which CC)
export FTN=$(which ftn)
env enable_mpi=ON enable_find_mpi=OFF enable_tests=OFF ./build_ascent.sh
```

Let me know if this helps. 

I don't know why, but occasionally when I use the script to rebuild only Ascent it will introduce new, problematic flags, and the only solution I've found is to reinstall everything. Though in my case it was introducing flags specific to gpus, so maybe that is not happening here.

**Comment by BenWibking** [comment]
Thanks, that might explain what was going on with my build earlier. I'll try this again once Frontier comes back online.

**Comment by BenWibking** [comment]
This worked for me. I'll close the issue.
