### ISSUE TITLE
How does ascent ghost region work internally?

### ISSUE THREAD

**Issue by wilsonCernWq** [Alpine-DAV/ascent#1165]
Hi,

I am reading the source [code](https://github.com/Alpine-DAV/ascent/blob/develop/src/libs/ascent/runtimes/ascent_main_runtime.cpp#L306-L316) about how ascent ghost region is configured internally. However, it seems when we include multiple `"ghost_field_name"`, the `m_ghost_fields` is actually not populated. Is this actually a bug or this case is handled elsewhere?

```
   if(options.has_path("ghost_field_name"))
    {
      if(options["ghost_field_name"].dtype().is_string())
      {
        m_ghost_fields.reset();

        std::string ghost_name = options["ghost_field_name"].as_string();
        m_ghost_fields.append() = ghost_name;
      }
      else if(options["ghost_field_name"].dtype().is_list())
      {
        const int num_children = options["ghost_field_name"].number_of_children();
        for(int i = 0; i < num_children; ++i)
        {
          const conduit::Node &child = options["ghost_field_name"].child(i);
          if(!child.dtype().is_string())
          {
            ASCENT_ERROR("ghost_field_name list child is not a string");
          }
        }
      }
      else
      {
        ASCENT_ERROR("ghost_field_name is not a string or a list");
      }
    }
```

My background is, I want to implement a feature that allows ascent to temporaily include some additional ghost field names everytime I call `execute`. Currently my hack is I include a new field called `m_persistent_field_names` in the main runtime class, and setup this field instead of the `m_field_names` field in the `Initialize` function. Then I reassemble the `m_field_names` in the publish function based on the data in `m_persistent_field_names` and some custimized info I include in the input mesh. I am wondering if this will cause any unwanted implications.

Thanks
Qi

**Comment by cyrush** [comment]
@wilsonCernWq  that looks like a clear bug, for the list case we clearly omit adding each entry.  I'll get this fixed, thanks for the report and sorry for the confusion related to this.

**Comment by wilsonCernWq** [comment]
@cyrush You are welcome! Thanks for confirming it. I just want to provide some additional information that, I implemented the proposed fix on my side, and then I encountered some vtkm issue related to volume rendering on some test examples (something like unsupported cellset). It took me a while to realize it was caused by me reusing this code:
https://github.com/Alpine-DAV/ascent/blob/b842516d12640e4a0d9433a18c7249440ef6fc3d/src/tests/t_utils.hpp#L504-L538

In this test case, `cell_ghosts` for the mesh is not correctly assigned (it seems it only assigns ghost values to the first 2voxels), so after passing through the ghost stripper, the volume become completely unstructured, making VTKm unable to render (at least for VTKm 2.0). I believe you would also encounter the same issue in regression tests. This issue was probably not caught because Ascent omited all the other ghost field names.

But if we make sure the `cell_ghosts` is correctly implemented, volume rendering should work just fine.

**Comment by cyrush** [comment]
@wilsonCernWq thank you for the extra info, the ghost fields there are a bit strange, but I think the intent was to test a simple case. 

In #1174, I updated the test to show a better view of where the ghost elements are removed. I also added a test that does volume rendering.

So volume rendering looks to be working even for the unstructured mesh result  -- we made some changes to ghost processing, hopefully that resolved residual issues you where seeing. 

Can you let me know if you see further issues with volume rendering?

**Comment by wilsonCernWq** [comment]
It seems working for me now. I will close the issue. Thank you!
