### ISSUE TITLE
Is there anyway to turn off the dataset_bound?

### ISSUE THREAD

**Issue by yslan** [Alpine-DAV/ascent#1185]
As title, I'm trying to remove the bounding box frame.
I tried dataset_bound = [0,0,0,0,0,0] but it's appear to be only active when the dataset_bound is larger than the data set dimension?

**Comment by yslan** [comment]
I guess one could try to set `dataset_bound = [-100.0,100.0,-100.0,100.0,-100.0,100.0]` to make it less visible, but it's still there.

**Comment by nicolemarsaglia** [comment]
Yes, there is! What you're wanting to do is turn off the World Annotations: https://ascent.readthedocs.io/en/latest/Actions/Examples.html?highlight=annotations#an-example-of-rendering-with-no-world-annotations

We also have a way to turn off the color bar via Screen Annotations: https://ascent.readthedocs.io/en/latest/Actions/Examples.html?highlight=annotations#an-example-of-rendering-with-no-screen-annotations

The dataset_bound is more so for the use case where the bounds are changing every time step and you want to normalize them.

**Comment by yslan** [comment]
Oh, I see. I should search "Annotations" as keywords. 
Thanks!

**Comment by nicolemarsaglia** [comment]
> Oh, I see. I should search "Annotations" as keywords. Thanks!

I'm going to add a link in the docs that has the dataset_bounds point to the annotations for clarity. I can see how that would be misleading.
