### ISSUE TITLE
vtkm2.1rc2 build notes

### ISSUE THREAD

**Issue by nicolemarsaglia** [Alpine-DAV/ascent#1210]
Latest Ascent branch built against VTKm 2.1rc2 on Frontier. No changes needed for build to succeed. Typical tests failing. e.g. MPI because not on node.  

![Screenshot 2023-10-27 162208](https://github.com/Alpine-DAV/ascent/assets/24232495/4f4e7951-cd11-429d-b265-693fda0ed6d4)

Gradient and Slice tests have different annotations, may just be frontier. 
![diff_tout_exaslice_3d100](https://github.com/Alpine-DAV/ascent/assets/24232495/73678edc-08eb-4b4a-8535-09d2febf77d7)
![diff_tout_gradient_mag_radial100](https://github.com/Alpine-DAV/ascent/assets/24232495/e8f9d637-1d30-4db8-aba6-b14b1ddf5406)
![diff_tout_slice_3d100](https://github.com/Alpine-DAV/ascent/assets/24232495/260908c1-c64a-4695-9eff-d6c5dcd7c835)

ascent_render_3d and ascent_pipeline_failure have noticeable differences, but correct, attributing these diffs to the arch. 

In memory one is new, looks like baseline is super zoomed in. Probably needs to be updated. 

![tout_in_memory_extract_render_slice_3d100](https://github.com/Alpine-DAV/ascent/assets/24232495/ed4322d8-9062-4526-bd58-caf87d330e59)

**Comment by cyrush** [comment]
Closing since we have made the move to VTK-m 2.1
