### ISSUE TITLE
Build fails with `targets already defined`

### ISSUE THREAD

**Issue by jhgoebbert** [Alpine-DAV/ascent#1215]
Hello everyone,

while building Ascent with Camp/2023.06.1 I came across the error `Some (but not all) targets in this export set were already defined.` when I set both CAMP_DIR and RAJA_DIR.
(this does not occur with Camp/2022.10.1)

The trace starts in `[ASCENT]/cmake/Setup3rdParty.cmake` when
- first, the call of `[ASCENT]/cmake/thirdparty/SetupCamp.cmake`  defines the targets `blt::blt_stub, blt::cuda, blt::cuda_runtime` and
- second, the call of `[ASCENT]/cmake/thirdparty/SetupRAJA.cmake -> [RAJA]/cmake/raja/raja-config.cmake -> [RAJA]/cmake/raja/bltTargets.cmake` expects them not to exist - but they are already defined.

So blt fails with an error:
```
CMake Error at RAJA/2022.10.5-GCCcore-11.3.0/lib/cmake/raja/bltTargets.cmake:42 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: blt::blt_stub, blt::cuda, blt::cuda_runtime

  Targets not yet defined: blt::openmp

Call Stack (most recent call first):
  RAJA/2022.10.5-GCCcore-11.3.0/lib/cmake/raja/raja-config.cmake:74 (include)
  CMake/3.26.3-GCCcore-11.3.0/share/cmake-3.26/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  cmake/thirdparty/SetupRAJA.cmake:26 (find_dependency)
  cmake/Setup3rdParty.cmake:68 (include)
  CMakeLists.txt:132 (include)
  ```

which comes from these lines in `[RAJA]/cmake/raja/bltTargets.cmake`:
```
# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS blt::blt_stub blt::cuda blt::cuda_runtime blt::openmp)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)
```

**Comment by jhgoebbert** [comment]
The same issue occurs when adding Umprise 2022.10.0 or 2023.06.0 

```
CMake Error at Umpire/2022.10.0-GCCcore-11.3.0/lib/cmake/umpire/bltTargets.cmake:42 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: blt::blt_stub, blt::cuda, blt::cuda_runtime

  Targets not yet defined: blt::openmp

Call Stack (most recent call first):
  Umpire/2022.10.0-GCCcore-11.3.0/lib/cmake/umpire/umpire-config.cmake:38 (include)
  cmake/thirdparty/SetupUmpire.cmake:21 (find_package)
  cmake/Setup3rdParty.cmake:61 (include)
  CMakeLists.txt:132 (include)
```

**Comment by jhgoebbert** [comment]
This seems to be similar to an older issue I found at ParaView: 
https://gitlab.kitware.com/paraview/paraview/-/issues/21129

**Comment by cyrush** [comment]
@jhgoebbert what combo of libraries and options you using?

There are a few issues with cmake setup across RAJA + Umpire versions that can be tricky. 

First, if you enable RAJA you also must have Umpire (that might not be obvious, or enforced by our build system)

This script shows the versions we build and test, it could help you with picking the right combo of libs for your builds:


https://github.com/Alpine-DAV/ascent/blob/develop/scripts/build_ascent/build_ascent.sh

**Comment by jhgoebbert** [comment]
Hi @cyrush,

thank you for your answer and the link.
I tried to have all versions set to the same as you have, but I might have missed something - will double check it again.
```
Python/3.10.4
CUDA/11.7
CMake/3.23.1

Conduit/0.8.8
Camp/2022.10.1
RAJA/2022.10.4
Umpire/2022.10.0
VTKm/2.0.0

Ascent/0.9.2
```
Perhaps CMake is the troublemaker. What CMake version do you use?

**Comment by cyrush** [comment]
Thanks for the details. CMake 3.23 should work fine. 

For a CUDA build - I suggest trying ENABLE_OPENMP=OFF for Umpire and RAJA.

**Comment by jhgoebbert** [comment]
Yes, great! This way it builds :) 
... but this only succeeded by setting ENABLE_OPENMP=OFF for Ascent, too.

I spend some more time and could find out, that ENABLE_OPENMP has to be set to the same value (ON/OFF) for Camp, RAJA, Umpire and Ascent to build (for the above mentioned reason). This way I can build Ascent now with OpenMP enabled :)

Thank you for your help

**Comment by cyrush** [comment]
Thanks for the update and I am glad you were able to find the right path.

These all need to be consistent, we should provide better error messages when they are not, but that might require tweaks to the individual projects.

**Comment by jhgoebbert** [comment]
For anyone who comes across this:
The main outcome is `ENABLE_OPENMP has to be set to the same value (ON/OFF) for Camp, RAJA, Umpire and Ascent to build`
