### ISSUE TITLE
Build with `ENABLE_FORTRAN=ON` fails in tests/ascent/fortran/CMakeLists.txt

### ISSUE THREAD

**Issue by jhgoebbert** [Alpine-DAV/ascent#1218]
Hello everyone,

Just to have it mentioned.
I tried to enable Fortran with `ENABLE_FORTRAN=ON` for Ascent and get the following error:
```
CMake Error in tests/ascent/fortran/CMakeLists.txt:
  Target "ascent" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "include/umpire"
```

Umpire/2022.10.0 was build with the following options:
```
-DCMAKE_VERBOSE_MAKEFILE=ON 
-DBUILD_SHARED_LIBS=ON 
-DENABLE_CUDA=ON 
-DCMAKE_CUDA_ARCHITECTURES="%(cuda_cc_cmake)s" 
-DENABLE_OPENMP=ON 
-DENABLE_FORTRAN=ON 
-Dcamp_DIR=${EBROOTCAMP} 
```

**Comment by cyrush** [comment]
Thanks, we don't use Umpire Fortran support -- I'll look at smoothing this out. 

-Cyrus

**Comment by jhgoebbert** [comment]
Ah, I see. I just have to disable Fortran in Umpire. Ok, I will do that.
Thanks

**Comment by jhgoebbert** [comment]
Ah, I see. I just have to disable Fortran in Umpire. Ok, I will do that.
Thanks
