### ISSUE TITLE
error with in-memory conduit extract test on macos

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#1229]
![Screenshot 2023-11-30 at 9 21 50 AM](https://github.com/Alpine-DAV/ascent/assets/1194526/710f5c04-3664-4635-aad1-e3fe5152d4af)

Looks like the slice isn't being applied, or we aren't rendering the result of the slice.

**Comment by nicolemarsaglia** [comment]
Ooo ya, I saw this in #1210, but did a worse job of documenting it. 

The diff is giving smash bros. 
![download](https://github.com/Alpine-DAV/ascent/assets/24232495/c1ec219f-05b8-4d17-8578-32f76fd06084)

**Comment by cyrush** [comment]
That is super funny that its the Smash Bros Logo!

**Comment by cyrush** [comment]
resolved in #1232
