### ISSUE TITLE
blueprint expects connectivity to be ints, 64 bit connectivity support

### ISSUE THREAD

**Issue by mlohry** [Alpine-DAV/ascent#1233]
I require 64 bit indexing for connectivity, and have compiled VTK-m with `-DVTKm_USE_64BIT_IDS=ON` because of this.

When building conduit, I hit the assertions

```
/Users/mlohry/dev/ascent/src/libs/ascent/runtimes/ascent_vtkh_data_adapter.cpp:2027:40: error: static assertion failed: blueprint expects connectivity to be ints
 2027 |         static_assert(sizeof(vtkm::Id) == sizeof(int), "blueprint expects connectivity to be ints");
      |                       ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
/Users/mlohry/dev/ascent/src/libs/ascent/runtimes/ascent_vtkh_data_adapter.cpp:2027:40: note: the comparison reduces to '(8 == 4)'
/Users/mlohry/dev/ascent/src/libs/ascent/runtimes/ascent_vtkh_data_adapter.cpp:2053:40: error: static assertion failed: blueprint expects connectivity to be ints
 2053 |         static_assert(sizeof(vtkm::Id) == sizeof(int), "blueprint expects connectivity to be ints");
      |                       ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
/Users/mlohry/dev/ascent/src/libs/ascent/runtimes/ascent_vtkh_data_adapter.cpp:2053:40: note: the comparison reduces to '(8 == 4)'
```

Questions:

1. Can ascent handle 64 bit indexes, and I'm just misconfiguring something? 
2. If ascent cannot presently handle 64 bit indexes, can it be made to do so?
3. Is it actually true that conduit-blueprint expects 64 bit indexes? Looking at conduit, it appears the default typedef for `conduit_index_t` is in fact 64 bit.

**Comment by cyrush** [comment]
We can fix this, adapt in the case that connectivity does not match what VTK-m needs regardless of underlying type. 

On most platforms we compile with `ints` are 64-bits, Windows is the main exception i know of, what platform are you compiling on?

**Comment by mlohry** [comment]
platform:

```
~/dev/ascent/build$ sysctl -n machdep.cpu.brand_string
Apple M2 Max
~/dev/ascent/build$ sw_vers
ProductName:		macOS
ProductVersion:		13.6.2
BuildVersion:		22G320
```

**Comment by cyrush** [comment]
thanks & is this with clang or gcc (I noticed you also hit #730, which seems to be unique to gcc on macos)

**Comment by mlohry** [comment]
This is with homebrew gcc-12, and the "classic" xcode linker.

#730  I've temporarily worked around by commenting out the `template class FLOW_API DataWrapper<conduit::Node>` declaration.

**Comment by haampie** [comment]
Seems to happen in Spack CI too:

https://gitlab.spack.io/spack/spack/-/jobs/9702178

`ascent@0.9.1` with GCC 11.4.0 on Ubuntu 20.04 / x86_64 with `vtk-m@1.9.0`.

(Edit: ok, in that case vtk-m was forced to have 64 bits ints... nevermind)

**Comment by mlohry** [comment]
Hi @cyrush , looking back I'm unclear on this statement

> On most platforms we compile with ints are 64-bits

but it looks like the build state now is that ascent requires VTKm to be built with `-DVTKm_USE_DEFAULT_TYPES_FOR_ASCENT=ON` which is incompatible with `-DVTKm_USE_64BIT_IDS=ON`, so I takethis to mean the only thing supported today is 32-bit ids, not 64, is that right? Any plans for 64 bit index support in the near future or should I work around it for now?

**Comment by cyrush** [comment]
@mlohry  that is correct, I am sorry I had this flipped in my brain.

We should remove the limit as to how VTK-m is compiled and in our expected use. 

We should move to admit both styles, acknowledging that one may be more performant (since VTK-m needs a primary selection) 

I will see if we can get this done in 0.9.3.

We are waiting on a few key third party libs updates (raja) to release 0.9.3.

**Comment by mlohry** [comment]
Sounds good @cyrush , I'll work around it for the time being. Happy to test a branch fix when the time comes.

**Comment by cyrush** [comment]
I looked into this:
That logic was preventing VTK-m dataset with non `int` connectivity from being converted back to Blueprint. 

Blueprint does support a broad range of integer types as connectivity arrays -- this logic in Ascent is a hold over from a while back. I am removing the guard in #1290.

Additionally, Ascent does accept non `int` connectivity from Blueprint meshes and can convert those to VTK-m. So round trip between these formats should not be an issue.

**Comment by cyrush** [comment]
resolved in https://github.com/Alpine-DAV/ascent/pull/1290

**Comment by mlohry** [comment]
Thank you @cyrush !!
