### ISSUE TITLE
Performance regression with kokkos?

### ISSUE THREAD

**Issue by yslan** [Alpine-DAV/ascent#1252]
Hi, 

I was running the same cases with two versions of Ascent on 1 node of Frontier.

- Version A: ascent/0.8.0, with openmp
(/sw/frontier/spack-envs/base/modules/spack/cray-sles15-x86_64/cray-mpich/8.1.23-levqyky/gcc/12.2.0)

- Version B: ascent/0.9.2-develop, with kokkos-HIP
(/sw/frontier/ascent/modulefiles)

I found the HIP version is much slower. You can see the solver time (elapsed - Ascent) is merely the same (200s)
```
                    ElapsedTime  AscentTime
Frontier Version A     294.6s      91.94s 
Frontier Version B     456.2s      255.3s  
```

I wonder if anyone observe similar things, or if I missed something here.

**Comment by yslan** [comment]
Ok, I tried to use 
```
  "timings"         : "true"
```

ascent_actions.yaml
[trigger_render.txt](https://github.com/Alpine-DAV/ascent/files/14302797/trigger_render.txt)

timing from rank0
[frontier_hip_timer.txt](https://github.com/Alpine-DAV/ascent/files/14302779/frontier_hip_timer.txt)
[frontier_openmp_timer.txt](https://github.com/Alpine-DAV/ascent/files/14302780/frontier_openmp_timer.txt)

**Comment by cyrush** [comment]
@yslan  in this case is the data passed to ascent already on the device & how large is data size?

Can add a 'save_info` action -- to get a yaml file with some more details. 

Looking at the breakdown, the specifics steps are pretty close, it looks like there is a big chunk of time that isn't being captured by the detailed timers.

**Comment by yslan** [comment]
False alert...
I messed up with the trigger condition so it's not apple to apple comparison.

It's actually amazing to see Ascent gets similar timing as Polaris one since we know the data size on A100 needs to be larger to get better performance.

This is a small case that has 62 millions points, or 45M hex cell.
And, yes, everything is already on device.
```
                    ElapsedTime  AscentTime
Frontier OpenMP     294.6s      91.94s 
Frontier HIP        232.5s      31.98s  
Polaris-CUDA        117.5s      31.82s     
```

**Comment by cyrush** [comment]
@yslan  thanks for the update and great to know you were able to understand the differences!
