### ISSUE TITLE
Docker images do not work on Mac's M* processors

### ISSUE THREAD

**Issue by mvictoras** [Alpine-DAV/ascent#1263]
Images need to be rebuilt for multiple targets. Probably something like this:

```
$ docker buildx build \
--push \
--platform linux/arm/v7,linux/arm64/v8,linux/amd64 \ --tag your-username/multiarch-example:buildx-latest .
```

Documentation here: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by cyrush** [comment]
@mvictoras thanks for this report. 

For our last tutorial, I did a step to build for multiple arches and combine them, but I think that failed. 

Can you try this image from docker hub?

```
alpinedav/sc23_jupyter:ubuntu-22.04-arm64_2023-11-10-sha42c201
```

**Comment by cyrush** [comment]
@mvictoras  
I created combined arch images for the 0.9.3 release.

Would you mind testing if `alpinedav/ascent-jupyter:0.9.3` works for you?

**Comment by mvictoras** [comment]
Sir, you are a magician.

It works

**Comment by cyrush** [comment]
Awesome, thanks for confirming!
