### ISSUE TITLE
equivalent of VisIt's connected components labeling?

### ISSUE THREAD

**Issue by BenWibking** [Alpine-DAV/ascent#1271]
Is there an equivalent to VisIt's connected components labeling `conn_components(Mesh)` and summary query `Query("Connected Components Summary")` in Ascent?

Ideally, I'd like to replicate the connected components VisIt tutorial inline with Ascent: https://visit-sphinx-github-user-manual.readthedocs.io/en/stable/tutorials/CCL.html.

**Comment by cyrush** [comment]
Ascent does not have a distributed memory connected components labeling like VisIt. Something I would love to add, but we have many things in the queue to work on before.

**Comment by BenWibking** [comment]
Ok, thanks for the info. I'll close for now.
