### ISSUE TITLE
Are crinkle slices / subvolumes supported?

### ISSUE THREAD

**Issue by mlohry** [Alpine-DAV/ascent#1279]
Is there a capability to do the equivalent of a crinkle slice in paraview, or extract subvolumes of the mesh cells as they're given without any cutting or interpolation?

I'm working with very large and highly unstructured mixed element meshes, and slice pipelines end up (1) creating an order of magnitude more vertices and connectivities than a crinkle slice would which is also increasing the runtime, and (2) obfuscates what the original mesh looks like.  Same goes for with clip pipelines.

i.e., I would like to be able to specify a slice or subvolume/bounding box, and the output of that be any cell that intersects that slice but with the original 3D connectivity and data.

**Comment by cyrush** [comment]
@mlohry You can use a threshold to extract subvolumes w/o cutting, but that is based on a field value. VisIt has a box operator that executes a threshold using a bounding box, will that suffice your cases in Ascent?

**Comment by mlohry** [comment]
@cyrush The visit box operator looks like it would fill most of our use cases. Sometimes we have a desire for slightly more complex shapes, like a box/plane not cartesian-aligned, or a cylindrical area of some orientation, but a box covers most use cases.

For our mixed element meshes, would that write the mixed elements as-is when writing to file, but for renders do the tetrahedralization mentioned in #1261 and https://github.com/visit-dav/visit/issues/19417?

**Comment by cyrush** [comment]
Thanks -- I will plan on extending the threshold filter with options for box and and plane to start. 

We would aim to keep the mesh as is (not change elements), but we need to update visit and ascent to support mixed element meshes.

**Comment by cyrush** [comment]
@mlohry vtk-m has a filter that should provide the foundation of what you are asking for, so I am extending Ascent's threshold filter to take the same spatial options as the clip filter. 

I have it wired up - but I am hitting a road block consuming the output. 
I pinged the VTK-m folks for advice.

**Comment by mlohry** [comment]
Awesome, thanks!

**Comment by cyrush** [comment]
This is being added in #1281.

It does require a patch to use with vtk-m 2.1, our build_ascent and spack based testing builds will both be using that patch and we will share it

**Comment by cyrush** [comment]
resolved in #1281

Requires patch to VTK-m 2.1:
https://github.com/Alpine-DAV/ascent/blob/0aef6cffd522be7419651e6adf586f9a553297d0/scripts/build_ascent/2024_05_03_vtkm-mr3215-ext-geom-fix.patch

**Comment by cyrush** [comment]
For examples of use, see our new threshold tests:

https://github.com/Alpine-DAV/ascent/blob/e69d6ec77938846caae8fea7ed988b1151ac9b81/src/tests/ascent/t_ascent_threshold.cpp#L207
