### ISSUE TITLE
Found that 'name' var should be ofile_base, v0.9.3

### ISSUE THREAD

**Issue by stephdempsey** [Alpine-DAV/ascent#1311]
We hit a build issue whith v0.9.3 that required a simple patch.  Patch details are inline. 

git diff src/libs/dray/utils/appstats.cpp
diff --git a/src/libs/dray/utils/appstats.cpp b/src/libs/dray/utils/appstats.cpp
index a9c8826d..c4683b38 100644
--- a/src/libs/dray/utils/appstats.cpp
+++ b/src/libs/dray/utils/appstats.cpp
@@ -261,7 +261,7 @@ StatStore::write_point_stats(const std::string &ofile_base)
   file.close();
   m_point_stats.clear();
 #else
-  (void) name;
+  (void) ofile_base;
 #endif
 }

**Comment by cyrush** [comment]
resolved in #1327

Thanks for reporting!
