### ISSUE TITLE
Clarification on what must be present across ranks

### ISSUE THREAD

**Issue by rpmcnally** [Alpine-DAV/ascent#1323]
From previous discussions, I was under the impression that a topology did not have to be present on all ranks to be used in ascent.  However, attempting to skip topologies that are not present on the local rank, ascent appears to die when trying to determine the global_bounds.  Am I incorrect?  Does the general structure of the mesh/actions need to match on all ranks, just with different leaf values?

I've created a reproducer which contains a Python executable and two data directories, 'partial' and 'full'.  In the 'partial' directory, topologies without any elements on the local rank are not present in the mesh node, so the associated fields and actions that target those topologies are also missing.  In the 'full' directory, every rank has all nodes present but many just have empty connectivity/values.
[missingNodes.tar.gz](https://github.com/user-attachments/files/16113116/missingNodes.tar.gz)

On my box, I'm executing it like this:
`mpirun -np 8 python3 test.py <directory>`

When executed with the 'full' directory, I get the extracts as expected.  When executed with the 'partial' directory, I get a an abort and stacktrace:
```
libascent_mpi.so(_ZNK6ascent14VTKHCollection13global_boundsEv+0x1e5) [0x7f1d2ae4d6d5]
Assertion failed in file src/mpi/datatype/typerep/src/typerep_yaksa_pack.c at line 285: element_size < 0 || *actual_unpack_bytes % element_size == 0
```

Semi-related, but I also discovered that using relay to save/load the nodes with empty connectivity/values does not work.  When written, the node contains an empty array of the appropriate type and passes validation.  After loading, it contains an empty node and fails validation.  The test.py script works around this by adding empty arrays after the nodes were populated with load().

**Comment by cyrush** [comment]
@rpmcnally thanks for the detailed description and the reproducer. 

To clear this up, here are the two preconditions you need to know:

- The actions must match across MPI tasks. 
- If an MPI task does not have a field, or topology, etc -- omit it, don't provide part of the structure with empty values.


You can think of the actions applying to union of the domains/typologies/fields across all MPI tasks. 
It's ok if one MPI task lacks a field you want to plot, Ascent handles that case and will skip any domains that aren't in play.

We want to avoid partial trees with empty leaves b/c a) the extra info really isn't needed, b) it can be confusing like in the i/o case you shared. 

Attached is an example that provides a single actions file that runs on the "partial" data.

[missing_nodes_cyrus.tar.gz](https://github.com/user-attachments/files/16168326/missing_nodes_cyrus.tar.gz)

**Comment by rpmcnally** [comment]
Thank you very much for the explanation and the example.  Now that I see it, it makes perfect sense.

**Comment by cyrush** [comment]
you are welcome --  happy this helped!
