### ISSUE TITLE
cuda failure when rendering 2d uniform grids

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#134]
`t_ascent_mpi_render_2d` and the  `t_python_ascent_mpi_render` both fail when cuda is enabled. 

Poking a bit, in `ascent_vtkh_data_adapter.cpp:VTKHDataAdapter::UniformBlueprintToVTKmDataSet`

Something down stream isn't happy with the structured cell set for the 2d case.
Here is the logic which creates it.  @mclarsen traced this a bit, and I believe hit an assert failure about being able to resize an array. 

```
    if(is_2d)
    {
      vtkm::Id2 dims2(dims[0], dims[1]); 
      vtkm::cont::CellSetStructured<2> cell_set(topo_name.c_str());
      cell_set.SetPointDimensions(dims2);
      result->AddCellSet(cell_set);
    }
    else
    {
      vtkm::cont::CellSetStructured<3> cell_set(topo_name.c_str());
      cell_set.SetPointDimensions(dims);
      result->AddCellSet(cell_set);
    }
```

**Comment by cyrush** [comment]
note: the test cases above fail in the pseudocolor plot, but I also tested the mesh plot and it failed as well.

**Comment by cyrush** [comment]
Note: we cant test this w/o mpi in the mix -- I am going to change the mpi tests and move the failing case into t_ascent_render_2d

**Comment by cyrush** [comment]
For the record, in #133 I did move this case to the non-mpi 2d case, so we can test it there

**Comment by mclarsen** [comment]
#146
