### ISSUE TITLE
docs missing an example image for partitioning

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#1340]
missing:
https://ascent.readthedocs.io/en/latest/Actions/Actions/examples/partition.png

**Comment by cyrush** [comment]
@nicolemarsaglia Q: found a missing image in the docs, do you have one we could use ?

**Comment by nicolemarsaglia** [comment]
@cyrush I'll see what I can come up with

**Comment by cyrush** [comment]
resolved in #1339
