### ISSUE TITLE
mpi ifdef bug in replay

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#1380]
`MPI_C_BOOL` is used to send the C type `_Bool` which may not always be compatible with C++'s `bool`.

We should use `int` + `MPI_INT` & avoid `MPI_BOOL`.

**Comment by cyrush** [comment]
@emily-howell this is an issue on frontier with the new replay actions checking logic b/c it is setup to use `MPI_BOOL`

Using bool seems like a reasonable choice, but the details undermine this. 

We should refactor to use `MPI_INT` -- I have done that on the [task/2024_09_frontier](https://github.com/Alpine-DAV/ascent/tree/task/2024_09_frontier) branch.

**Comment by emily-howell** [comment]
Ah, good to know. Would you like to make a MR to merge in your branch with the fix?

**Comment by cyrush** [comment]
Yes -- but that branch is still an active battle, so once we get to success that will be the plan.

**Comment by cyrush** [comment]
Turns out, we had a #ifdef issue `ASCENT_MPI_ENABLED` is not defined in replay for the MPI case, but `ASCENT_REPLAY_MPI` is.

This is a very subtle difference broke the mpi version of relay.

Thanks to @mlohry for pointing out that `MPI_BOOL` does not exist in MPI--  which led me to the true mystery.

**Comment by cyrush** [comment]
resolved in #1383
