### ISSUE TITLE
2d test failure in debug mode

### ISSUE THREAD

**Issue by mclarsen** [Alpine-DAV/ascent#139]
This is sort of a note to myself. I believe the 2d failure is potentially do to a vtkm bug. What is happening is that the incoming data set has a field zero-copied. The data set in contained in a RenderContainer and is deleted by flow when it is not needed, but vtkm is trying to delete the underlying storage it does not own. Since it cannot, the pointer is not null which triggers:

`caught ErrorBadValue : User allocated arrays cannot be reallocated.
t_ascent_render_2d: /usr/workspace/wsb/larsen30/pascal/alpine/cuda_build/vtk-m/vtkm/cont/StorageBasic.cxx:257: void vtkm::cont::internal::StorageBasicBase::ReleaseResources(): Assertion `this->Array == nullptr' failed.`

`VTKM_ASSERT(this->Array == nullptr);`

**Comment by cyrush** [comment]
is this related to #134 ?

**Comment by mclarsen** [comment]
#146 resolves this issue.
