### ISSUE TITLE
The built-in cinema viewer page: cinema_databases/cinema_out/index.html appears disorganized and unresponsive

### ISSUE THREAD

**Issue by devilkingsatan666** [Alpine-DAV/ascent#1391]
I successfully generated a cinema database following the [WarpX Ascent In-Situ Tutorial](https://warpx.readthedocs.io/en/latest/dataanalysis/ascent.html), using WarpX version 24.09, instrumented with Ascent version 0.9.3, built using Spack. I modified the Spack recipe for AMReX to include Ascent and Conduit as variants.

However, as shown in the attached screenshots, the cinema viewer web page created alongside the database (located at cinema_databases/cinema_out/index.html) appears disorganized and unresponsive regardless of whether the page is served via a web server.

![image](https://github.com/user-attachments/assets/eab26c92-49ba-43ef-b41b-ddd15ef0740d) 
![image](https://github.com/user-attachments/assets/15e82148-e0dd-41de-992a-bb7e6cb8eca5) 
![image](https://github.com/user-attachments/assets/38c981b7-ddb8-4ba7-9d7f-270299b982ea) 
Best regards,
Wu-Cheng Chiang
National Central University, Taiwan (R.O.C.)

**Comment by cyrush** [comment]
It seems like the output is malformed -- extra text should not be there. Not sure why that is happening. The pages are created to avoid need for a webserver, so it should not matter if server is used or not.  We will check out cinema output routines.

**Comment by nicolemarsaglia** [comment]
@devilkingsatan666 I've duplicated this bug and it is definitely a weird one. For some reason all of the text from the cinema files are being appended to index.html. As a temporary workaround, if you copy a clean version of index.html or delete all the appended text (after the end of the html block on line 56), you should be able to view your database in the browser. https://github.com/Alpine-DAV/ascent/blob/c11da70c958bd9cdcc5d49eacbbc13c95a48ecef/src/libs/ascent/web_clients/cinema/index.html

Thanks for bringing this to our attention.

**Comment by devilkingsatan666** [comment]
@nicolemarsaglia @cyrush, Thank you so much for your great help! After implementing your suggestions, I can view the database correctly now! I explored the database elegantly via [Visual Studio Code](https://code.visualstudio.com/)'s "[Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)" plugin, as shown in the following image. Thank you so much!

![image](https://github.com/user-attachments/assets/1b782ac2-579c-4100-8921-d56886d72dd2)
Best regards,
Wu-Cheng Chiang
National Central University, Taiwan (R.O.C.)

**Comment by nicolemarsaglia** [comment]
Looks like a bug in one of our main dependencies. An issue ticket with a reproducer has been opened: https://github.com/LLNL/conduit/issues/1326

Current workaround is to edit the generated files or copy/download clean files from here after using cinema: https://github.com/Alpine-DAV/ascent/tree/c11da70c958bd9cdcc5d49eacbbc13c95a48ecef/src/libs/ascent/web_clients/cinema

**Comment by cyrush** [comment]
Ascent develop has a fix as of #1425
