### ISSUE TITLE
Extracts cannot access non-existent child

### ISSUE THREAD

**Issue by tmarrinan** [Alpine-DAV/ascent#1396]
I have set up a data set as follows:
```
conduit::Node data;

data["state/cycle"] = step;
data["state/time"] = time;

data["coordsets/coords/type"] = "uniform";
data["coordsets/coords/dims/i"] = dim_x;
data["coordsets/coords/dims/j"] = dim_y;

data["coordsets/coords/origin/x"] = offset_x;
data["coordsets/coords/origin/y"] = offset_y;
data["coordsets/coords/spacing/dx"] = 1;
data["coordsets/coords/spacing/dy"] = 1;

data["topologies/topo/type"] = "uniform";
data["topologies/topo/coordset"] = "coords";

// add fields and data...

ascent.publish(data);
```

However, when I attempt to execute an extract (any type) I get the following message:
```
[Error] Ascent::execute
message:
Cannot access non-existent child "values" from Node([0]/coordsets/coords)
```

As you can see, my coordsets/coords does not have "values", but those of type "uniform" shouldn't. Am I setting something up incorrectly, or is there a workaround for this error?

Any help would be greatly appreciated!

**Comment by tmarrinan** [comment]
OK, If I switch from "uniform" to "rectilinear" as follows:

```
uint32_t i;
double *grid_x = new double[dim_x];
double *grid_y = new double[dim_y];
for (i = 0; i < dim_x; i++) grid_x[i] = offset_x + i;
for (i = 0; i < dim_y; i++) grid_y[i] = offset_y + i;

conduit::Node data;

data["state/cycle"] = step;
data["state/time"] = time;

data["coordsets/coords/type"] = "rectilinear";
data["coordsets/coords/values/x"].set(grid_x, dim_x);
data["coordsets/coords/values/y"].set(grid_y, dim_y);

data["topologies/topo/type"] = "rectilinear";
data["topologies/topo/coordset"] = "coords";

// add fields and data...

ascent.publish(data);
```

Then the code runs (since "rectilinear" coordsets have explicit values).

Just wondering if Ascent does not work with "uniform" types? I'd prefer not to have to allocate and manually set the grid positions.

**Comment by nicolemarsaglia** [comment]
@tmarrinan that's an odd error. Ascent works with uniform meshes. I'm not sure why your data is not working. 

Can you post your actions file?

**Comment by tmarrinan** [comment]
No file - just defining in code as follows:

```
conduit::Node actions;
conduit::Node &add_extracts = actions.append();
add_extracts["action"] = "add_extracts";
conduit::Node &extracts = add_extracts["extracts"];

extracts["e1/type"] = "relay";
extracts["e1/params/path"] = output_filepath;
extracts["e1/params/protocol"] = "json";

ascent.execute(actions);
```

**Comment by tmarrinan** [comment]
Well, I have no idea what the issue was, but I rebuilt Ascent and it now works with "uniform" types too

**Comment by JustinPrivitera** [comment]
Strange. Glad you are no longer running into your issue though! Feel free to re-open if it comes up again.
