### ISSUE TITLE
paraview build clarification

### ISSUE THREAD

**Issue by mlohry** [Alpine-DAV/ascent#1432]
I'm trying to experiment with the paraview functionality, but I get stuck when it uses the system python3 and fails to import, `No module named 'paraview'`. If I go back to conduit and try to build with `-DPYTHON_EXECUTABLE=/opt/ParaView-5.11.0-MPI-Linux-Python3.9-x86_64/bin/pvpython` I get the following cmake error:

```
-- PYTHON_EXECUTABLE /opt/ParaView-5.11.0-MPI-Linux-Python3.9-x86_64/bin/pvpython
-- PYTHON_CONFIG_VERSION 
-- PYTHON_INCLUDE_DIR 
CMake Error at cmake/thirdparty/SetupPython.cmake:36 (MESSAGE):
  Reported PYTHON_INCLUDE_DIR does not exist!
```

Are there any examples of a barebones non-spack build with paraview? Also, the docs mention a `paraview-package-momentinvariants.patch`, is this required to function, or only for a particular feature?

**Comment by cyrush** [comment]
@mlohry  Kitware folks were helping support this during the ECP program, but I don't think they have funding for this. You could try to pulse them and see.

**Comment by mlohry** [comment]
Looks like Paraview Catalyst uses conduit blueprint data which I already have for ascent. Would using catalyst+paraview directly be a better supported workflow?

**Comment by cyrush** [comment]
Yes, that is a good path to try.  Catalyst should support live Paraview.

**Comment by mlohry** [comment]
Thanks!
