### ISSUE TITLE
add actions editor utility

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#164]
using conduit's python interface is ideal vs hand editing json, but on top of this we want a validation tool as well that helps us avoid parse errors and logic errors before an in situ run

**Comment by mclarsen** [comment]
Right now, replay kind of serves this purpose. You can save a relay extract then load it into replay and test out json actions.

**Comment by mclarsen** [comment]
#205 Demonstrates how to do this.

**Comment by cyrush** [comment]
I'll add a blurb to the docs.

**Comment by cyrush** [comment]
yaml support, replay, and jupyter support fill this need
