### ISSUE TITLE
change lib names for loepng and flow

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#178]
add ascent prefix (ascent_loepng + ascent_flow) to reduce change of name collision

**Comment by mclarsen** [comment]
@cyrush Didn't you do this?

**Comment by cyrush** [comment]
yes, however I didn't change header names for flow.  Felt it was a bit too much for the PR.

**Comment by cyrush** [comment]
closing, we won't add ascent_ prefix to the flow headers now
