### ISSUE TITLE
useless file in scripts/uberenv/packages/uberenv-ascent?

### ISSUE THREAD

**Issue by hankchilds** [Alpine-DAV/ascent#204]
in scripts/uberenv/packages/uberenv-ascent, there is a file called uberenv-ascent.tar.gz.  Looks like cruft.  Probably should be simply removed, but wanted to bring it to the attention of the team in case it is a symptom of some larger problem.

Its contents are:
" tar.vim version v29
" Browsing tarfile /Users/hank/ascent/scripts/uberenv/packages/uberenv-ascent/uberenv-ascent.tar.gz
" Select a file with cursor and press ENTER

gzip: /Users/hank/ascent/scripts/uberenv/packages/uberenv-ascent/uberenv-ascent.tar.gz: not in gzip format

**Comment by mclarsen** [comment]
This file is part of the spack-based build system. Spack needs to "download" something and this is a stand in since the uberenv package inherits from ascent, which has already been downloaded.
