### ISSUE TITLE
should using-with-make Makefile include LD_LIBRARY_PATH hint?

### ISSUE THREAD

**Issue by hankchilds** [Alpine-DAV/ascent#206]
In the Makefile in src/examples/using-with-make, there is a very good set of comments about how to run the example.  That said, I found that there was a missing line, about setting LD_LIBRARY_PATH.  Should such a line be added?

Also, "To build" (line 50 of the Makefile) should probably read "To build and run".

Also, also: the last comment of ascent_render_example.cpp in that same directory should be "close ascent", not "close alpine".

**Comment by cyrush** [comment]
resolved, config.mk and makefiles now provide rpath options.
