### ISSUE TITLE
documentation on plots: add mesh, and should not include "zone"?

### ISSUE THREAD

**Issue by hankchilds** [Alpine-DAV/ascent#207]
I think the documentation is trying to use element of zone.

But one "zone" slipped through:
"We current have support for two plot types: pseudocolor and volume. Both plots support node centered and zone centered scalar fields. Plots optionally consume the result of a pipeline, but if none is specified, then the plot input is the published mesh data. Each scene can contain one or more plots."

https://ascent.readthedocs.io/en/latest/Actions/Scenes.html#pseudocolor

If everyone agrees this should say "element", then the documentation should be updated.

Also, there are three plots types (mesh).

**Comment by mclarsen** [comment]
#210 makes element the preferred nomenclature within the docs
