### ISSUE TITLE
Silent error for wrong field

### ISSUE THREAD

**Issue by hankchilds** [Alpine-DAV/ascent#209]
I called my field in my mesh "cellId", but I called accidentally in my plot within a scene directed it to use a field called "field."

I.e., 
    mesh["fields/cellId/association"] = "element";
    mesh["fields/cellId/topology"] = "mesh";
    mesh["fields/cellId/volume_dependent"] = "false";
    mesh["fields/cellId/values"].set_external(vals, 2);

And:
    scenes["s1/plots/p1/type"] = "pseudocolor";
    scenes["s1/plots/p1/field"] = "field";

The result was an empty scene.

I set up a Conduit error handler, thinking that is what I needed to see Ascent error messages.

Is there a way to issue an error message here?  (I.e., no silent error)

**Comment by mclarsen** [comment]
#212 Fixes this. Ascent will now throw errors when the field for a plot does not exist. Additionally, filters with invalid fields will also throw errors and bad color table names induces a warning to the user and falls back to the default color table.
