### ISSUE TITLE
typo in online documentation

### ISSUE THREAD

**Issue by hankchilds** [Alpine-DAV/ascent#219]
In https://ascent.readthedocs.io/en/latest/Actions/Extracts.html,
the relay HDF5 code says:
extracts["e1/params/protocol"] = "blueprint/mesh/hd5f";
but it should say hdf5, not hd5f.

**Comment by cyrush** [comment]
thanks! 
Some time in the near future, I will move to get all of this snippets tested, and have the docs directly pull in excerpts. That will keep us honest with testing

**Comment by cyrush** [comment]
resolved in #222
