### ISSUE TITLE
Travis reporting false positives

### ISSUE THREAD

**Issue by mclarsen** [Alpine-DAV/ascent#243]
@cyrush see https://travis-ci.org/Alpine-DAV/ascent/jobs/481041811

vtkm has mpi on by default.

**Comment by cyrush** [comment]
@mclarsen thanks, this is the result of the last spack update. Should we pin to vtkm~mpi?

**Comment by mclarsen** [comment]
I am changing the vtkm package to have mpi off be default.

**Comment by cyrush** [comment]
Good, doing that in our uberenv copy should solve for now. Next time we do a spack update, we can make sure to say we depend on vtkm~mpi there as well

**Comment by mclarsen** [comment]
It should never be on by default since it does not have any mpi functionality.

**Comment by cyrush** [comment]
kitware folks added it as the default with their last update --  maybe we should suggest it be false in spack proper?

**Comment by mclarsen** [comment]
Spack failures are still reporting as passed for some reason.

**Comment by cyrush** [comment]
closing since we are now using azure
