### ISSUE TITLE
Using with make example tries to include mfem make config without mfem installed

### ISSUE THREAD

**Issue by mclarsen** [Alpine-DAV/ascent#248]
https://github.com/Alpine-DAV/ascent/blob/782e426de6e61248dfbbed137e6a7661c47605c9/src/config/ascent_config.mk.in#L136

**Comment by mclarsen** [comment]
I thought I had fixed this, but there is still and issue.

**Comment by cyrush** [comment]
Ugh, if statements in Makefiles are a mystery:

The ifeq pattern seems ok, recommended here:

https://stackoverflow.com/questions/38801796/makefile-set-if-variable-is-empty/38832692

**Comment by cyrush** [comment]
that if statement checks if it is empty, I think we just need an else. 

I'll work on resolving it.
