### ISSUE TITLE
add debug print statement to vtk-h or vtk-m to check if exception is commonly encountered

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#249]
Seeing the following error in ./tests/ascent/t_ascent_mpi_slice 

Error: TryExecute encountered an error: ErrorBadValue (User allocated arrays cannot be reallocated.)
	- Failing functor: N4vtkm4cont6detail16ArrayCopyFunctorE
	- Failing device: Serial

Hypothesis: this should be caught and handled more than we expect.

Crash happens b/c of issues with MPI + stack unwinding on Cyrus' machine.

**Comment by mclarsen** [comment]
@cyrush Did we fix this?

**Comment by cyrush** [comment]
this was resolved with #282
