### ISSUE TITLE
Missing vtk-h libraries

### ISSUE THREAD

**Issue by stevenwalton** [Alpine-DAV/ascent#259]
I'm going through another ascent build (on develop branch) and finding that it is erroring out on some vtk-h libraries. 

First off there seems to be an error in
`ascent/src/rover/vtkm_typedefs.hpp:68` where `vtkm::cont::Timer<>` has some additional angle brackets `<>` and complains about `Timer` not being a template. Checking the vtk-h file confirms this. Easy fix.

The next errors come in with `ascent/src/rover/partial_image.hpp` where we have three libraries that **do not exist in vtk-h**. They are 
`vtkh/rendering/{Absorption,Emission,Volume}Partial.hpp`
I rolled back a few commits on vtk-h and didn't see them there. 

I'm on the most up-to-date ascent and vtk* versions
ascent: d41516a
vtk-h: ef25274
vtk-m: 03fc3d5

**Comment by stevenwalton** [comment]
Looking at the commits ab89951 says that they were moved to vtkh and that's where `partial_image.hpp` was added. 

Looks like `ascent/src/rover/partial_image.hpp` was also edited in 83cf8a6

I would suspect that there hasn't been a good build since that time. This is the same day as the vtk-h commit [f3979a1](https://github.com/Alpine-DAV/vtk-h/commit/f3979a18759bbd5d617b4e4e8ba45e6a914631ff). 

Changing the paths to `vtk/rendering/compositing/*` strangely does not resolve the issue.

**Comment by cyrush** [comment]
@stevenwalton 

Here are the blessed versions we currently use and test:

vtk-h: version('ascent_ver', commit='f3979a1', submodules=True, preferred=True)

vtk-m: version('ascent_ver', commit='774957e8', preferred=True)


(from)
https://github.com/Alpine-DAV/ascent/tree/develop/scripts/uberenv/packages

**Comment by stevenwalton** [comment]
What's the conduit version? I'm using 0c30223, like the docs say, and have an error about missing `conduit_relay_mpi.hpp`. This version of conduit doesn't have the mpi relay in `include/conduit`. But I do notice that this is in the current commit of conduit. 

Is ascent now always using the current version of conduit?

**Comment by cyrush** [comment]
Latest conduit should be fine - sounds like your conduit install is missing mpi support. Ascent with mpi needs conduit with mpi. Sorry if that detail is missing from the building docs.




On March 2, 2019 at 6:57:02 PM PST, Steven Walton <notifications@github.com> wrote:

What's the conduit version? I'm using 0c30223, like the docs say, and have an error about missing conduit_relay_mpi.hpp. This version of conduit doesn't have the mpi relay in include/conduit. But I do notice that this is in the current commit of conduit.

Is ascent now always using the current version of conduit?

**Comment by stevenwalton** [comment]
This builds fine but when trying the mini-apps I get errors.

I have current ascent (d41516a), vtk-m (774957e), vtk-h (f3979a), and current conduit (ec67a2e). 

Build conduit first, vtk-m, then h, then ascent.

host-config is used in all builds. 
```
set(CMAKE_C_COMPILER "/usr/bin/mpicc" CACHE PATH "")
set(CMAKE_CXX_COMPILER "/usr/bin/mpicxx" CACHE PATH "")
set(CMAKE_Fortran_COMPILER "/usr/bin/mpifort" CACHE PATH "")
set(ENABLE_OPENMP OFF CACHE BOOL "")
set(ENABLE_MPI ON CACHE BOOL "")
set(MPI_C_COMPILER "/usr/bin/mpicc" CACHE PATH "")
set(MPI_CXX_COMPILER "/usr/bin/mpicxx" CACHE PATH "")
set(MPI_Fortran_COMPILER "/usr/bin/mpifort" CACHE PATH "")

set(ENABLE_FORTRAN ON CACHE BOOL "")
set(ENABLE_CUDA OFF CACHE BOOL "")
set(ENABLE_PYTHON OFF CACHE BOOL "")
#set(CONDUIT_DIR "/home/walton/Programming/src/conduit/build/" CACHE PATH "")
set(CONDUIT_DIR "/home/walton/Programming/install/conduit" CACHE PATH "")
#set(VTKM_DIR "/home/walton/Programming/src/vtk-m/build" CACHE PATH "")
set(VTKM_DIR "/home/walton/Programming/install/vtk-m" CACHE PATH "")
#set(VTKH_DIR "/home/walton/Programming/src/vtk-h/build" CACHE PATH "")
set(VTKH_DIR "/home/walton/Programming/install/vtk-h" CACHE PATH "")
```

Running cloverleaf or lulesh gives an error about `libvtkm_rendering-1.2.so.1` not being found. VTK-m installs `libvtkm_rendering-1.3.so` (looks like it has for awhile, it is 1.3 when I was doing adios builds). To fix this problem shouldn't we look for `libvtkm_rendering` and have that soft link to the version? (improvement?) Creating a `1.2.so.1` softlink that points to 3 and updating `LD_LIBRARY_PATH` does not resolve the issue. 

As another note, it seems that conduit, vtk-{m,h} need to have install directories to run with ascent. I did notice that what's built into a build directory for conduit is completely different than what goes into an install. 

Edit: I also built with bootstrap and went to the build-debug/examples/proxies and ran both and I get `OPAL ERROR: Not initialized in file pmix2x_client.c` and some MPI errors. This can be fixed by running the mpi version that the bootstrap environment installs. So I _think_ this is working? But that wasn't straight forward.
Btw, running another locate seems to show that this also built the 1.3 version.

Is there some way I can stay up to date with the versions you are building? I feel like a lot of the problems we run into here (UO) are because of version mismatching.

**Comment by cyrush** [comment]
@stevenwalton  You are correct that all of those libs need to be installed, we can't pull them in in their build layouts. 

If it is asking for vtk-m 1.2 -- something is crossed. I suspect if you do a LDD on the lulesh example things would like quite strange.  Are you sure you have clean build? I would start over with a new build directory. 


Also, you can't mix versions of MPI -- that leads to very strange results.  If bootstrap built MPI and used it to build conduit + vtkh, you will need to use that MPI for ascent. 

There is way you can provide your desired MPI to spack (which is used by bootstrap), here is an example of a `packages.yaml` file that does this for one of LLNL's systems:

https://github.com/Alpine-DAV/ascent/blob/develop/scripts/uberenv/spack_configs/toss_3_x86_64_ib/packages.yaml

For next steps, it would be good to get a `packages.yaml` and `compilers.yaml` setup for your UO systems, that way you can rely on those to give you an automated build.

**Comment by stevenwalton** [comment]
> If it is asking for vtk-m 1.2 -- something is crossed.

I thought that was odd as well. 

> LDD on the lulesh example things would like quite strange. 

There's a couple of odd thing to me: 
1) is that my source build has 36 results and the bootstrap build has 42. The difference in depends are `librover_mpi`, `libpython2.7` (we're not using 3?), `libgomp`, `libhdf5`, `libz`, `libpciaccess`, `libxml2`, `liblzma`, `libiconv`. Most of these look fine to me though.
2) The source build has both `libvtkm_rendering-1.3.so.1` and `libvtkm_rendering-1.2.so.1`. Same with `libvtkm_cont`. Source also has a `libibverbs`.

> Are you sure you have clean build?

Well the `src` directory referenced in my host-config file was created and populated (using git clones) on Friday. Same with the `install` dir (deleted these folders several times too to clean and restart). The bootstrap build is in a different folder from the source ascent too. I can try again though, doesn't hurt. 

I'll try out the yaml file method and see if that can give me a less cumbersome build. Seems like this might be a more reliable way. And if I understand correctly the bootstrap method will always call the uberenv packages and thus I'll always have the "safe" versions?

Would it help if I updated the docs and submitted a PR?

**Comment by cyrush** [comment]
If you have both `libvtkm_rendering-1.3` and `libvtkm_rendering-1.2` refs then something somewhere was linked to an older version of VTK-m. 


Here is an example from my vtk-m isntall:
```
[harrison37@elder ascent (task/2019_02_python_extract_module)]$ ls -l uberenv_libs/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/vtkm-ascent_ver-y734uckypxt3u264gw4xg2iyjzfbtdxn/lib/
total 11944
drwxr-sr-x  3 harrison37  51976       96 Feb  6 13:17 cmake
-rwxr-xr-x  1 harrison37  51976  1478984 Feb  6 13:17 libvtkm_cont-1.3.1.dylib
lrwxr-xr-x  1 harrison37  51976       24 Feb  6 13:17 libvtkm_cont-1.3.dylib -> libvtkm_cont-1.3.1.dylib
-rwxr-xr-x  1 harrison37  51976  4630704 Feb  6 13:17 libvtkm_rendering-1.3.1.dylib
lrwxr-xr-x  1 harrison37  51976       29 Feb  6 13:17 libvtkm_rendering-1.3.dylib -> libvtkm_rendering-1.3.1.dylib
```

Default build uses python2.7, however you can build with python3 (and we test this in our Travis)

Instead of using bootstrap, we recommend just calling the ubrerenv.py script directly:

https://ascent.readthedocs.io/en/latest/QuickStart.html

You will need to use the `spack-config-dir` option to pass it your compiler and packages settings:

https://ascent.readthedocs.io/en/latest/BuildingAscent.html#building-with-uberenv

Also, ever time you use a new host-config, you should start with a new build directory - otherwise you won't get a clean cmake configure. 


Certainly  if you have suggestions of how to make this path clear int he docs, that would be awesome!

**Comment by mclarsen** [comment]
Steven has a successful build so I am closing this.
