### ISSUE TITLE
Copy and paste error in src/ascent/runtimes/ascent_vtkh_data_adapter.cpp

### ISSUE THREAD

**Issue by freemalloc** [Alpine-DAV/ascent#277]
Error message is wrong, looks like a copy and paste error. 
Right now the numbers are the same, but the code tells you they are different.

In file: src/ascent/runtimes/ascent_vtkh_data_adapter.cpp
line 1172 (is the second line)

        ASCENT_INFO("Field '"<<field_name<<"' number of values "<<num_vals<<
                    " does not match the number of cells "<<nverts<<". Skipping");

nverts should be neles.

The ASCENT_INFO... on line 1171 is a copy of the line 1162, but missed the change of match variable name.

David Camp

**Comment by cyrush** [comment]
thanks for the report @freemalloc , we will tackle this!

**Comment by mclarsen** [comment]
@cyrush Close?

**Comment by cyrush** [comment]
resolved in #278
