### ISSUE TITLE
Update repo topics

### ISSUE THREAD

**Issue by hauten** [Alpine-DAV/ascent#313]
A new page on the LLNL software portal (https://software.llnl.gov/radiuss/) will soon dynamically pull in RADIUSS repos. To achieve this, we need RADIUSS-related repos outside the LLNL org to be tagged with relevant topics. See https://github.com/LLNL/llnl.github.io/issues/17, https://github.com/LLNL/llnl.github.io/issues/151, & https://github.com/LLNL/llnl.github.io/blob/new-home-page/radiuss/README.md for additional context.

Ascent already has `data-vis`. Please also add `radiuss`.

**Comment by IanLee1521** [comment]
Done.

**Comment by IanLee1521** [comment]
Ping @cyrush

**Comment by cyrush** [comment]
@IanLee1521 it's there, forgot to close this issue

**Comment by IanLee1521** [comment]
Thanks Cyrus!
