### ISSUE TITLE
PNG encoding issue (1 channel)

### ISSUE THREAD

**Issue by stevenwalton** [Alpine-DAV/ascent#327]
I'm reading these files with Python PIL and I noticed that if I look at `img.mode` that `theta_3.78_6.png` is type P and a single channel where `theta_5.68_5.png` is type RGB and has 3 channels. The first image is also half the size of the second one even though they are both 1024.

Mac's inspector shows that both are "Color mode:" = RGB but that the former has "ColorSync profile = sRGB IEC61966-2.1" while the latter doesn't. I believe there is something happening in the compression of the images that makes them different. Inspector says all information is the same except for size and ColorSync profile.

This image is [1024x1024x1]

![theta_3 78_6](https://user-images.githubusercontent.com/4933582/61828487-ab221b80-ae1b-11e9-97b6-5fc3c742c41f.png)

This image is [1024x1024x3]

![theta_5 68_5](https://user-images.githubusercontent.com/4933582/61828489-ab221b80-ae1b-11e9-9a94-3fced5b20d2d.png)

**Comment by mclarsen** [comment]
I will investigate what lodepng is doing.

**Comment by mclarsen** [comment]
Superficial observation: the top image has only blue while the bottom one has more.

**Comment by cyrush** [comment]
i think this is simply how lodepng was setup to encode (for space efficiency) and is part of the standard -- it seems client code will need to figure out how to digest the data?

**Comment by mclarsen** [comment]
All of this is part of the PNG standard. Taking a superficial look at the code, it seems like lodepng is making some sort of choice about the bit depth.
