### ISSUE TITLE
Building from a mainline spack environment

### ISSUE THREAD

**Issue by wspear** [Alpine-DAV/ascent#329]
@mclarsen I am working on incorporating ascent/vtkm/vtkh etc into an environment populated using spack. My understanding is the main spack repos aren't well supported for ascent and related tools so I'm trying to figure out my best option to proceed. I've tried copying over the package.py files for ascent and vtkh but this fails because they request vtkm ascent_ver which isn't provided by the vtkm package (and I didn't see an alternate package). Any ideas? Thanks!

**Comment by mclarsen** [comment]
@wspear These are the packages we maintain: 
https://github.com/Alpine-DAV/ascent/tree/develop/scripts/uberenv/packages

vtkm is included in this lists and is what we use to build our dependencies.

**Comment by cyrush** [comment]
@wspear is this for e4s? do you have any driving deadlines for getting things correct (release dates, etc)

We can help get things working if we know the driving timelines.

**Comment by wspear** [comment]
@cyrush yes. We are targeting the current round of package integration for the end of October.

**Comment by cyrush** [comment]
@wspear thanks, we can certainly get things ready given that timeline.

**Comment by cyrush** [comment]
@wspear closing this, while we still rely on our fork for most of our development, several fixes were put into spack develop to help with building ascent.
