### ISSUE TITLE
make -j

### ISSUE THREAD

**Issue by mclarsen** [Alpine-DAV/ascent#33]
`make -j` does not always work. 

When starting from a clean build, the build system tries to copy the fortran module before it is created and all subsequent makes fail.

To resolve, you must `make clean` and `make`

**Comment by cyrush** [comment]
Was this gfortan? 

Some older versions of gfortran do something strange with intermediate output file names, causing object files to clobber each other (using some global loc, instead of the working dir) If you can reproduce with a given platform and compiler, let me know.

**Comment by cyrush** [comment]
Some more details about this issue were discussed in:
https://github.com/LLNL/blt/issues/72

**Comment by zbeekman** [comment]
I took a quick look through the Fortran sources and CMake files. I don't think that the problem @mclarsen reported is related to LLNL/blt#72 or https://gitlab.kitware.com/cmake/cmake/issues/17525.

To know for sure, more detail including an error message would be helpful. But, from searching for Fortran sources and then reading `CMakeLists.txt`s it looks like Fortran source files defining modules are *NOT* being used in more than one CMake target which is required to trigger the "bug" I was talking about.

**Comment by cyrush** [comment]
@zbeekman thanks knowing this now, I agree thats not the issue. But our issue provides the same symptom, so its still a mystery.

**Comment by cyrush** [comment]
More bread crumbs:
https://stackoverflow.com/questions/11455942/cmake-copying-fortran-modules-failure-on-linux

**Comment by cyrush** [comment]
Example of this happening with gcc 4.9.3
```
/usr/workspace/wsa/hmc_17/tpls/chaos_5_x86_64_ib/spack/opt/spack/linux-rhel6-x86_64/gcc-4.9.3/cmake-3.9.4-2wtqilrsopunhd55tjwvubux3v5k7yvy/bin/cmake -E cmake_copy_f90_mod fortran/ascent ascent/CMakeFiles/ascent.dir/ascent.mod.stamp GNU
Error copying Fortran module "fortran/ascent".  Tried "fortran/ASCENT.mod" and "fortran/ascent.mod".
```

**Comment by mclarsen** [comment]
The orln folks just hit this error

**Comment by cyrush** [comment]
what compiler are they using?

You should be able to solve by not doing a make -j.

In spack you can modify the packages to do  `make(parallel=False)`

**Comment by mclarsen** [comment]
So I reported this incorrectly. I just heard "fortran module does not exist" and thought that this was the issue. They did not build conduit with fortran enabled, so Ascent failed to find the conduit.mod file.

**Comment by cyrush** [comment]
ahh, we should make sure to smooth that out:

Check if Conduit has fortran support and throw an Error when Ascent has fortran enabled but Conduit was not built with it.

I created #89 to track this.

**Comment by cyrush** [comment]
the stackoverflow post above mentions that a bad include path triggered this. 

Seems odd, but it could be related to: https://github.com/LLNL/blt/issues/12

**Comment by cyrush** [comment]
Still seeing this:


Fatal Error: Can't rename module file '../fortran/ascent.mod0' to '../fortran/ascent.mod': No such file or directory

Error copying Fortran module "fortran/ascent".  Tried "fortran/ASCENT.mod" and "fortran/ascent.mod".

**Comment by zbeekman** [comment]
FYI, it looks like the logic in CMake is defined [here](https://gitlab.kitware.com/cmake/cmake/blob/master/Source/cmDependsFortran.cxx#L321-441) (approximately) for handling the copying of the stamp files.

As I stated before, I've always run into this when multiple targets build the same module, and as a work around I have successfully used "object libraries" when a given source file defining a module needs to be used in multiple targets.

Perhaps @bradking or @robertmaynard or one of the other @Kitware folks could help point us in the right direction for how to best debug this issue.

**Comment by bradking** [comment]
`ascent_fortran.f90` is compiled independently by two targets.  It is added to the `ascent_sources` list [here](https://github.com/Alpine-DAV/ascent/blob/df8c75b6a7f6332433689f6a94eea7d865f60639/src/ascent/CMakeLists.txt#L139).  Then it is used by the `ascent` library [here](https://github.com/Alpine-DAV/ascent/blob/df8c75b6a7f6332433689f6a94eea7d865f60639/src/ascent/CMakeLists.txt#L180) and the `ascent_mpi` library [here](https://github.com/Alpine-DAV/ascent/blob/df8c75b6a7f6332433689f6a94eea7d865f60639/src/ascent/CMakeLists.txt#L217).  This causes a race to generate `ascent.mod`.  The `Fortran_MODULE_DIRECTORY` needs to be set differently for the two targets.  Or, `ascent_fortran.f90` needs to be moved into a separate target (e.g. an object library) shared by the other two.  For example:

```patch
diff --git a/src/ascent/CMakeLists.txt b/src/ascent/CMakeLists.txt
index 8b72c9e..44bb3c3 100644
--- a/src/ascent/CMakeLists.txt
+++ b/src/ascent/CMakeLists.txt
@@ -136,7 +136,8 @@ endif()
 #############################
 
 if(FORTRAN_FOUND)
-    list(APPEND ascent_sources fortran/ascent_fortran.f90)
+    add_library(ascent_fortran OBJECT fortran/ascent_fortran.f90)
+    list(APPEND ascent_sources $<TARGET_OBJECTS:ascent_fortran>)
 endif()
 
 ################################
```

**Comment by cyrush** [comment]
@bradking Thank so you much for reviewing!  Such a simple error but I was blind to it for quite some time.

**Comment by cyrush** [comment]
@zbeekman @bradking object library did the trick, thanks again for spotting the issue!
