### ISSUE TITLE
Python inconcsistent errors with MPI

### ISSUE THREAD

**Issue by stevenwalton** [Alpine-DAV/ascent#332]
I'm getting inconsistent results and errors when using python. The code is almost identical to that in #324. I have noticed that the errors are more frequent the more cores I assign the task (I've kept on 1 node since I've noticed that this was faster for my task). Assigning 1 core I have yet to run into the problem. Assigning 4 cores I've run into the following error once out of 5 tests. I am running on Pascal and have been attempting to assign 32 cores. At 32 cores I do not get the below error but instead hangs where ascent outputs the python file (I cannot see any print statements, even those placed in the constructor). At 16 this is also a pretty common place to hang, but I have gotten one running and my simulation is continuing (after several attempts of resubmitting an identical job).

An interesting part is that the current modification in my code is that I'm waiting for the cycle to be > 72. I had gotten all the data < cycle=72 with 32 cores with no problems. 

```
[Error] Ascent::execute 
{
  "file": "/g/g20/walton16/Programs/ascent/build/spack/var/spack/stage/ascent-develop-fh3z725um3y2zt3dzzuuvux5kayfwdr5/ascent/src/flow/filters/flow_python_script_filter.cpp",
  "line": 398,
  "message": "python interpreter failure:<type 'exceptions.IOError'>\n{\n  \"file\": \"/g/g20/walton16/Programs/ascent/build/spack/var/spack/stage/conduit-master-pvhbwynqvqpucjr4fq4zzfisolduaux6/conduit/src/libs/conduit/conduit_generator.cpp\",\n  \"line\": 2250,\n  \"message\": \"JSON parse error: \\n parse error message:\\nThe document is empty.\\n offset: 0\\n line: 0\\n character: 0\\n json:\\n\\n\\n\"\n}\n\nTraceback (most recent call last):\n  File \"<string>\", line 262, in <module>\n  File \"<string>\", line 44, in __init__\n  File \"<string>\", line 169, in makeRootJson\n  File \"<string>\", line 202, in getRootJsonParams\nIOError: \n{\n  \"file\": \"/g/g20/walton16/Programs/ascent/build/spack/var/spack/stage/conduit-master-pvhbwynqvqpucjr4fq4zzfisolduaux6/conduit/src/libs/conduit/conduit_generator.cpp\",\n  \"line\": 2250,\n  \"message\": \"JSON parse error: \\n parse error message:\\nThe document is empty.\\n offset: 0\\n line: 0\\n character: 0\\n json:\\n\\n\\n\"\n}\n\n"
}

 Wall clock    5.1070880889892578     
 Average time per cell    1.8335995264351368E-005
 Step time per cell       7.2551192715764046E-006
 Step      69 time   1.8709828 control    sound    timestep   2.66E-02       1,       1 x  7.81E-02 y  7.81E-02
[Error] Ascent::execute 
{
  "file": "/g/g20/walton16/Programs/ascent/build/spack/var/spack/stage/ascent-develop-fh3z725um3y2zt3dzzuuvux5kayfwdr5/ascent/src/ascent/runtimes/ascent_main_runtime.cpp",
  "line": 640,
  "message": "Cannot add extract filter, extract named \"e1\" already exists"
}
```

Job script is as follows
```
#!/bin/bash
#SBATCH -J rotational
#SBATCH -N 1
#SBATCH -t 12:00:00
#SBATCH -p pvis
#SBATCH -o /p/lustre1/walton16/database73.out

srun -n 32 cloverleaf3d_par
```

Edit: (update on the 16 core run)

I'm not sure if this helps but there's also an inconsistency between Step and the cycle that python is giving me
```
if __name__ == '__main__':
    a = myAscent(resolution=100,
            rootdir="/p/lustre1/walton16/Database2/CloverLeaf/",
            )
    a.run()
    a._ascent.close()

 Wall clock    319.38344597816467     
 Average time per cell    1.0259799225758271E-003
 Step time per cell       1.7281931650359184E-002
 Step      77 time   2.0923744 control    sound    timestep   2.83E-02       1,       1 x  7.81E-02 y  7.81E-02
Got through rootdir: /p/lustre1/walton16/Database2/CloverLeaf/
set self.comm
Got mesh and ascnet
Clover.in exists: True
Did makeRootJson
Made ascent options
Set action file parameter
set mpicom
Opening ascent
MY CURRENT CYCLE IS: 76
We're on cycle: 76
Publushed
Made hdf5
made scenes
[/g/g20/walton16/Programs/ascent/build/spack/var/spack/stage/ascent-develop-fh3z725um3y2zt3dzzuuvux5kayfwdr5/ascent/src/flow/filters/flow_python_script_filter.cpp : 199]
 
{
  "interface": 
  {
    "module": "ascent_extract",
    "input": "ascent_data",
    "set_output": "ascent_set_output"
  },
```

This sim also froze at timestep 77. It created some images first, but did not generate all of them. SSHing in I only see 22% of the CPU used and 8.5GiB of memory used (no SWAP used).

**Comment by stevenwalton** [comment]
Looks like issue was write commands stepping on one another. Cleared up with @mclarsen. Will reopen if problem persists. There is a problem that the error doesn't always generate and we just have a block.

**Comment by mclarsen** [comment]
The problem was that the python environment is distributed, meaning that the python code is executed on all ranks. This issue arose when all ranks tried to read and write to the same file, resulting in non-deterministic behavior. Saying it another way, one rank threw an exception and all other ranks kept on going. The program froze at an MPI barrier where all the ranks that survived were waiting for the crashed rank == deadlock.
