### ISSUE TITLE
Reconsider publishing individual vector components in vtkm data adapter

### ISSUE THREAD

**Issue by mclarsen** [Alpine-DAV/ascent#348]
Scenario: vector components are published as three separate arrays.

During the blueprint to vtkm conversion, we are creating the vector field and separate fields for each, and since we zero copy all the memory, it costs nothing in terms of memory. What I failed to consider is that when we do any operation or convert it back to blueprint the memory ends up being duplicated (doubling the size of the memory), since vtkm / blueprint have no notion of the memory actually pointing to the same place.

**Comment by cyrush** [comment]
we could detect that case by looking at the mem addresses -  but in many cases the copy would happen and undermine? For example, if you do a threshold and push through all the fields, pretty sure copies will happen.

**Comment by mclarsen** [comment]
Yes. That was what I mean by any operation. Say we do a contour: vtkm maps the fields onto the new data set and it makes copies. That part is out of our control. I think it would be better to have a filter that explicitly extracts a vector component. That way, the user should at least expect that there will be a copy of what they asked for.

**Comment by mclarsen** [comment]
#482 Will add the ability to extract vector components and will remove the previous behavior.
