### ISSUE TITLE
Idea to keep pipeline result around

### ISSUE THREAD

**Issue by mclarsen** [Alpine-DAV/ascent#353]
Use case: I want to keep rendering, but could be something like I want to run a simulation on the result.

Have a special extract that can touch the Ascent runtime. Just like we have `source`, we could have a `sink` where the sink converts the pipeline result back to blueprint and makes it accessible. This would let us create a new instance of ascent where we just continually re-render the results from a new camera angle without re-running the pipeline.

**Comment by cyrush** [comment]
sink can become a named source :-)

**Comment by cyrush** [comment]
resolved in #1147 -- we now have the conduit extract, which supports use cases like this
