### ISSUE TITLE
removal of "space" while creating cinema databases

### ISSUE THREAD

**Issue by ayanbiswas** [Alpine-DAV/ascent#382]
Currently, cinema databases produced from ascent contain extra spaces in the header. Those spaces need to be removed for the cinema viewer to work correctly. 

This change needs to happen in ascent_runtime_vtkh_filters.cpp, line 429 (https://github.com/Alpine-DAV/ascent/blob/a86e6b975b1a52ab9922cd089947d1a5b7185f5b/src/ascent/runtimes/flow_filters/ascent_runtime_vtkh_filters.cpp#L429):
m_csv = "phi, theta, time, FILE\n";
should be 
m_csv = "phi,theta,time,FILE\n";

**Comment by mclarsen** [comment]
Done.
