### ISSUE TITLE
need to be able to explicitly set the image name for a render

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#395]
i tried "image_name", but that didn't seem to work.

We need a path were the user set the full file name. 

@mclarsen I feel like I am overlooking something, am I missing the right incantation?

**Comment by mclarsen** [comment]
Do you care if its overwritten each time?

**Comment by cyrush** [comment]
in this case thats exactly what I want (allow user to set fully control the filename)

**Comment by cyrush** [comment]
resolved in #397
