### ISSUE TITLE
docs issue: volume extract

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#396]
https://ascent.readthedocs.io/en/latest/Actions/Examples.html#an-example-of-using-the-volume-unstructured-grid-extract-with-min-and-max-values

"An example of using the volume (unstructured grid) extract with min and max values"

Should be volume plot.

**Comment by cyrush** [comment]
never-mind, this is rover  -- so it's valid, but confused me

**Comment by mclarsen** [comment]
I have been wanting to unify the volume rendering into a single call/plot, but its too complicated to get into this release i think. I can put it on the wish list.
