### ISSUE TITLE
cmake rpath issue in link.txt files after configure via spack

### ISSUE THREAD

**Issue by jeffmauldin** [Alpine-DAV/ascent#424]
(This is Jeff Mauldi at SNL, jamauld@sandia.gov)

I am working on a centos machine which is a virtual box machine (windows is host)
I was using gcc 8.2.1

I did a build from scratch via

python scripts/uberenv/uberenv.py --install --prefix="build"

and I started getting errors fairly deep into the process, in particular when building the packages ascent, conduit, and vtk-h.
The problem is associated with a problem with the link line where it references openmpi.  In particular, the link.txt file will have something like:

-Wl,/home/jamauld/ascent_insitu/ascent/build/spack/opt/spack/linux-centos8-sandybridge/gcc-8.2.1/openmpi-3.1.4-uob4cui5x3snemszj5f3lh3gdvj37lty/lib

and the compile step told me that this was a library not a file.  In looking at the link.txt files with the problem it looked like this should have been part of the rpath, so something like

-Wl,rpath,/home/jamauld/ascent_insitu/ascent/build/spack/opt/spack/linux-centos8-sandybridge/gcc-8.2.1/openmpi-3.1.4-uob4cui5x3snemszj5f3lh3gdvj37lty/lib

I hacked around the problem by having the package.py files directly alter the link.txt files after the cmake call and before the make call.  In my hack, I just added the openmpi lib directory to another rpath which was right next to it.  (there was a -Wl,rpath,blahblahblah and I added -Wl,rpath,blahblahblah:myopenmpilibfromabove/lib;)

I don't know why I was getting this error and nobody else might be, but I suspect it is because I was allowing spack to build my openmpi rather than using a preexisting one.  In any case, it needs to handle the rpath correctly and not skip arguments which cause the compile step to fail.

**Comment by cyrush** [comment]
@jeffmauldin thanks for the report!

It seems something went wrong with how CMake is detecting the MPI install that spack built. 

The best approach to packages like MPI is to reuse the system install. 

Here is the spack `packages.yaml` file  we used to build ascent on the virtual machine used for the SC19 tutorial:

https://github.com/Alpine-DAV/ascent/blob/develop/scripts/uberenv/spack_configs/lbnl/sensei-ascent-sc19/packages.yaml

You can pass this config as follows:

```
python scripts/uberenv/uberenv.py --install --prefix="build" --spack-config-dir=spack_configs/lbnl/sensei-ascent-sc19
```

The `packages.yaml` file outlines all of the packages already installed that we want to use.  You can create your own if you want to customize. 


If you still want to have spack build mpi, You could also try using mpich:

```
python scripts/uberenv/uberenv.py --install --prefix="build" --spec-%gcc ^mpich"
```

**Comment by cyrush** [comment]
closing, we have made many changes + improvements to cmake mpi logic. 
@jeffmauldin please open a new ticket if you encounter problems.
