### ISSUE TITLE
Building fails on power9

### ISSUE THREAD

**Issue by mdrocco** [Alpine-DAV/ascent#433]
Trying to build on Lassen (following README). First I get this warning:
```
==> Warning: gcc@4.9.3 cannot build optimized binaries for "power9le". Using best target possible: "power8le"
```
Then the process fails when building openblas, with a bunch of similar errors. Failing commands look like:
```
/g/g92/drocco2/repos/ascent/build/spack/lib/spack/env/gcc/gcc -Ofast -mcpu=power9 -mtune=power9 -mvsx -malign-power -fno-fast-math -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_WARMUP -DMAX_CPU_NUMBER=128 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.7\" -DASMNAME=scopy -DASMFNAME=scopy_ -DNAME=scopy_ -DCNAME=scopy -DCHAR_NAME=\"scopy_\" -DCHAR_CNAME=\"scopy\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c copy.c -o scopy.o
```
and produce the  following errors:
```
gcc: error: unrecognized argument in option '-mcpu=power9'
gcc: note: valid arguments to '-mcpu=' are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 [...] native power3 power4 power5 power5+ power6 power6x power7 power8 powerpc powerpc64 powerpc64le rs64 titan

gcc: error: unrecognized argument in option '-mtune=power9'
gcc: note: valid arguments to '-mtune=' are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 [...] native power3 power4 power5 power5+ power6 power6x power7 power8 powerpc powerpc64 powerpc64le rs64 titan
```
I guess I could fix by enforcing a newer gcc. I tried with `module load gcc/8.3.1 && export CC=gcc` but it had no effect.

**Comment by mclarsen** [comment]
I got this warning on Summit, but it built fine for me. I was using a newer version of gcc (5.4). I think we need to create a spack config file for Lassen, which I believe would solve your issue.

**Comment by mdrocco** [comment]
Thanks @mclarsen! Meanwhile, is there a "quick and dirty" way to force a newer gcc?

**Comment by mclarsen** [comment]
Sorry for the slow response. If you know spack, you can try to create a spack config file for Lassen.

Here is an example of rzansel: https://github.com/Alpine-DAV/ascent/blob/develop/scripts/uberenv/spack_configs/llnl/rzansel/compilers.yaml

If you are not familiar with spack, the either you can build the deps yourself or I will have time to create a spack config file on Tuesday. I assume you are looking for a cuda build?

**Comment by mdrocco** [comment]
Thanks! I will try adapting a spack file for Lassen.

For now, I just need to build and run Laghos, not necessarily with GPU support.

**Comment by mclarsen** [comment]
just to make sure that we are on the same page, the command you will need to run will look something like this:
`python ./scripts/uberenv/uberenv.py --spack-config-dir=./path_to_your_compilers.yaml --spec=+mfem`

**Comment by mdrocco** [comment]
I am working on the spack for lassen on my fork (I will create a pull request when ready).

With gcc@8.3.1, building fails on `mfem` stage with: (stage log [here](https://github.com/Alpine-DAV/ascent/files/3969558/spack-build-out.txt), full log [here](https://github.com/Alpine-DAV/ascent/files/3969603/build-gcc%408.3.1.log))
```
undefined reference to `_gfortran_concat_string'
```

With gcc@4.9.3, building fails on `openblas` stage with: (stage log [here](https://github.com/Alpine-DAV/ascent/files/3969594/spack-build-out.txt), full log [here](https://github.com/Alpine-DAV/ascent/files/3969606/build-gcc%404.9.3.log))
```
gcc: error: unrecognized argument in option '-mcpu=power9'
```

**Comment by mclarsen** [comment]
@droccom I split the difference and created a config for gcc/7.3.1. I just added it to develop.
It worked for me:

```
python scripts/uberenv/uberenv.py --spack-config-dir=./scripts/uberenv/spack_configs/llnl/lassen/ --spec=+mfem~python
mkdir build
 cd build/
 cmake -C ../uberenv_libs/lassen709-blueos_3_ppc64le_ib_p9-gcc@7.3.1-ascent.cmake ../src/
```
The cmake file name that it generates for you, assuming it builds, will be different. Let me know if this works.

**Comment by mdrocco** [comment]
Thanks @mclarsen! The config works smoothly.
