### ISSUE TITLE
A build error (ubuntu 16)

### ISSUE THREAD

**Issue by hpcfmh105** [Alpine-DAV/ascent#438]
>> 383    ld: cannot find /home/adios/ascent/build/spack/opt/spack/linux-ubun
            tu16.04-sandybridge/gcc-5.4.0/openmpi-3.1.4-tcblinsos5yyrudgitomcob
            x7ibexejb/lib: File format not recognized
  >> 384    collect2: error: ld returned 1 exit status
     385    blt/tests/smoke/CMakeFiles/blt_mpi_smoke.dir/build.make:91: recipe
            for target 'tests/blt_mpi_smoke' failed
  >> 386    make[2]: *** [tests/blt_mpi_smoke] Error 1

I was able to nail down the error about the command " -Wl,/home/adios/ascent/build/spack/opt/spack/linux-ubuntu16.04-sandybridge/gcc-5.4.0/openmpi-3.1.4-tcblinsos5yyrudgitomcobx7ibexejb/lib". - if I replace -Wl with -L, it seems that everything would be fine. Any suggestions?

/usr/bin/g++-5      -O2 -g -DNDEBUG  -rdynamic -Wl,-rpath -Wl,/home/adios/ascent/build/spack/opt/spack/linux-ubuntu16.04-sandybridge/gcc-5.4.0/hwloc-1.11.11-24jr3hxmuxdbjxnzhlvcm2mmsyy3lp33/lib -Wl,/home/adios/ascent/build/spack/opt/spack/linux-ubuntu16.04-sandybridge/gcc-5.4.0/openmpi-3.1.4-tcblinsos5yyrudgitomcobx7ibexejb/lib -L/home/adios/ascent/build/spack/opt/spack/linux-ubuntu16.04-sandybridge/gcc-5.4.0/hwloc-1.11.11-24jr3hxmuxdbjxnzhlvcm2mmsyy3lp33/lib -L/home/adios/ascent/build/spack/opt/spack/linux-ubuntu16.04-sandybridge/gcc-5.4.0/openmpi-3.1.4-tcblinsos5yyrudgitomcobx7ibexejb/lib -pthread CMakeFiles/blt_mpi_smoke.dir/blt_mpi_smoke.cpp.o  -o ../../../tests/blt_mpi_smoke -Wl,-rpath,/home/adios/ascent/build/spack/opt/spack/linux-ubuntu16.04-sandybridge/gcc-5.4.0/openmpi-3.1.4-tcblinsos5yyrudgitomcobx7ibexejb/lib /home/adios/ascent/build/spack/opt/spack/linux-ubuntu16.04-sandybridge/gcc-5.4.0/openmpi-3.1.4-tcblinsos5yyrudgitomcobx7ibexejb/lib/libmpi.so /home/adios/ascent/build/spack/opt/spack/linux-ubuntu16.04-sandybridge/gcc-5.4.0/openmpi-3.1.4-tcblinsos5yyrudgitomcobx7ibexejb/lib/libmpi_cxx.so /home/adios/ascent/build/spack/opt/spack/linux-ubuntu16.04-sandybridge/gcc-5.4.0/openmpi-3.1.4-tcblinsos5yyrudgitomcobx7ibexejb/lib/libmpi_usempif08.so /home/adios/ascent/build/spack/opt/spack/linux-ubuntu16.04-sandybridge/gcc-5.4.0/openmpi-3.1.4-tcblinsos5yyrudgitomcobx7ibexejb/lib/libmpi_usempi_ignore_tkr.so /home/adios/ascent/build/spack/opt/spack/linux-ubuntu16.04-sandybridge/gcc-5.4.0/openmpi-3.1.4-tcblinsos5yyrudgitomcobx7ibexejb/lib/libmpi_mpifh.so

**Comment by mclarsen** [comment]
Sorry for the slow response. Can you provide the command you used to invoke the build?

**Comment by hpcfmh105** [comment]
I just followed the quick start in the documentation, and used conmmand  "python scripts/uberenv/uberenv.py --install --prefix="build" ". And then this error appeared when I used the spack to compile.

**Comment by mclarsen** [comment]
We have had problems with openmpi in the past. Try to build with mpich:

```
python scripts/uberenv/uberenv.py --install --prefix="build" --spec=" ^mpich"
```

**Comment by hpcfmh105** [comment]
Okay thank you. Seems to work, the installation is successful.
