### ISSUE TITLE
Spack, ascent, conduit and python

### ISSUE THREAD

**Issue by mclarsen** [Alpine-DAV/ascent#448]
-- PYTHON found!! /global/u2/n/nicmars/Camera/ascent/uberenv_libs/spack/opt/spack/cray-cnl7-haswell/gcc-8.2.0/conduit-master-7p5i626jfwbmenxhl3mic47fausawy57
CMake Error at cmake/thirdparty/SetupConduit.cmake:121 (message):
  conduit python import failure:

Call Stack (most recent call first):
  cmake/Setup3rdParty.cmake:69 (include)
  CMakeLists.txt:146 (include)

**Comment by cyrush** [comment]
Was this during a spack build, or using an uber build post?

I wonder if conduit wasn't "activated" or if there was some crossing of python installs at play. 

check importing conduit from python found gen_spack_env_script + sourcing "s_env.sh"?

**Comment by mclarsen** [comment]
Nichole saw this on Cori, and I have seen this on my laptop.

**Comment by cyrush** [comment]
best course is to try import conduit in the python interp outside of the build system as a sanity check

**Comment by mclarsen** [comment]
This is the magic:
```
python scripts/gen_spack_env_script.py python py-pip
source s_env.sh 
```
use the gen script to create a environment bash script that puts python in your path. Source that script and configuring conduit and ascent with the spack python works.s
