### ISSUE TITLE
Show built-in color tables in ascent docs

### ISSUE THREAD

**Issue by kennyweiss** [Alpine-DAV/ascent#473]
The ``ascent`` docs list the built-in color tables (See: https://ascent.readthedocs.io/en/latest/Actions/Scenes.html#color-tables)

It would be really helpful if the docs also showed images of the built-in color tables.

**Comment by mclarsen** [comment]
I'll add them to the docs, but in the mean time:
![Black - Blue - White](https://user-images.githubusercontent.com/4038129/76691432-ed48d900-6607-11ea-9242-013ecc158062.png)
![Black-Body Radiation](https://user-images.githubusercontent.com/4038129/76691434-ede16f80-6607-11ea-88fb-03fb3e72e5fe.png)
![Blue - Green - Orange](https://user-images.githubusercontent.com/4038129/76691435-ede16f80-6607-11ea-8da9-b776bcf0854b.png)
![Blue to Orange](https://user-images.githubusercontent.com/4038129/76691436-ee7a0600-6607-11ea-9e0a-3a87c778d1d6.png)
![Cold and Hot](https://user-images.githubusercontent.com/4038129/76691437-ee7a0600-6607-11ea-8279-3b84dc27ba80.png)
![Cool to Warm Extended](https://user-images.githubusercontent.com/4038129/76691439-ee7a0600-6607-11ea-94cd-3504f95d8e02.png)
![Cool to Warm](https://user-images.githubusercontent.com/4038129/76691440-ef129c80-6607-11ea-9224-f1796c7c2cdf.png)
![Default](https://user-images.githubusercontent.com/4038129/76691441-ef129c80-6607-11ea-8179-583da3acf5fd.png)
![Gray to Red](https://user-images.githubusercontent.com/4038129/76691442-ef129c80-6607-11ea-9b25-dbca2cc2f613.png)
![Green](https://user-images.githubusercontent.com/4038129/76691443-ef129c80-6607-11ea-9d7b-f6441bf5a0b3.png)
![Inferno](https://user-images.githubusercontent.com/4038129/76691444-efab3300-6607-11ea-858d-53324278791d.png)
![Jet](https://user-images.githubusercontent.com/4038129/76691445-efab3300-6607-11ea-9065-f4f80a41cb40.png)
![Plasma](https://user-images.githubusercontent.com/4038129/76691446-efab3300-6607-11ea-80b9-1f1c02623810.png)
![Rainbow Desaturated](https://user-images.githubusercontent.com/4038129/76691447-f043c980-6607-11ea-8dba-99e4eac4ce05.png)
![Rainbow Uniform](https://user-images.githubusercontent.com/4038129/76691448-f043c980-6607-11ea-8868-bfd90c010bfa.png)
![Viridis](https://user-images.githubusercontent.com/4038129/76691449-f043c980-6607-11ea-9898-8e9459ba9d3f.png)
![X Ray](https://user-images.githubusercontent.com/4038129/76691451-f043c980-6607-11ea-89c6-a4a82f45109b.png)
![Yellow - Gray - Blue](https://user-images.githubusercontent.com/4038129/76691452-f0dc6000-6607-11ea-981b-d03fdc55e168.png)

**Comment by mclarsen** [comment]
These files have the color table names.
[vtkm_color_tables.tar.gz](https://github.com/Alpine-DAV/ascent/files/4333407/vtkm_color_tables.tar.gz)

**Comment by mclarsen** [comment]
#462 mega pr adds the docs

**Comment by mclarsen** [comment]
https://ascent.readthedocs.io/en/latest/Actions/VTKmColorTables.html
