### ISSUE TITLE
Allow `refinement_level` of 1 in ascent_options

### ISSUE THREAD

**Issue by kennyweiss** [Alpine-DAV/ascent#475]
I got the following error when I set ``refinement_level: 1`` in ``ascent_options.yaml``:
```
Error" <ascent>/src/ascent/runtimes/ascent_main_runtime.cpp:214:
	'refinement_level' must be greater than 1
```

I think ``refinement_level: 1`` should be allowed since 
* sometimes "HO meshes" can have an order 1
* users might want to see a very coarse representation of their HO mesh.

If this is a limitation on ``mfem``'s side, would it be possible for ``ascent`` to handle this transparently so that the result is equivalent to a ``refinement_level`` of 1?

**Update:** It looks like ``refinement_level: 1`` works correctly, but produces an error message each time ascent runs. So, I think this ticket would be satisfied by simply removing the error message.

**Comment by mclarsen** [comment]
@kennyweiss What was the error message at 'refinement_level: 1'? I just changed it to verify that refinement is greater than 0 (at 0 mfem has problems) and it worked for me.

**Comment by mclarsen** [comment]
#476

**Comment by kennyweiss** [comment]
Thanks @mclarsen 

I'm pretty sure it was the one that you found in  ``src/ascent/runtimes/ascent_main_runtime.cpp`` in #476 

```cpp
Error" <ascent>/src/ascent/runtimes/ascent_main_runtime.cpp:214:
	'refinement_level' must be greater than 1
```
