### ISSUE TITLE
Add better error messages to things like renders.

### ISSUE THREAD

**Issue by mclarsen** [Alpine-DAV/ascent#500]
Its an error if there is no `image_prefix` or `image_name`. Provide the expected path in the error message: `s1/renders/r1` is missing ....

**Comment by mclarsen** [comment]
@cyrush how does this look: 
```
Render (s1/renders/r1) must have either a 'image_name' or 'image_prefix' parameter
```

**Comment by cyrush** [comment]
looks good +1

**Comment by mclarsen** [comment]
I am also altering the flow filter 'unique' names to better reflect the path.
