### ISSUE TITLE
error installing Ascent and its dependencies on mac OS X

### ISSUE THREAD

**Issue by JoyboyWang** [Alpine-DAV/ascent#529]
I cloned the latest develop branch and tried to install it on macOS Catalina 10.15.4 following the Quick Start. But I got the following error:

<code>
FileNotFoundError: [Errno 2] No such file or directory: '/Users/joe/Downloads/ascent/build/spack/lib/spack/spack/config.py'
</code>

It seems that the python file is needed for installation but I don't have it.

Here is the full log:
<code>
python3[uberenv project settings: {'package_name': 'ascent', 'uberenv_package_name': 'uberenv-ascent', 'spack_url': 'https://github.com/alpine-DAV/spack', 'spack_branch': 'task/2019_11_update_ascent', 'spack_activate': {'py-numpy': ['+python'], 'py-pip': ['+python'], 'py-mpi4py': ['+python', '+mpi'], 'conduit': ['+python'], 'py-sphinx': ['+python', '+doc']}, 'spack_clean_packages': ['vtkm', 'vtkh', 'conduit']}]
[uberenv options: {'install': True, 'prefix': 'build', 'spec': None, 'mirror': None, 'create_mirror': False, 'spack_config_dir': None, 'project_json': '/Users/joe/Downloads/ascent/scripts/uberenv/project.json', 'ignore_ssl_errors': False, 'spack_pull': False, 'spack_clean': False, 'run_tests': False, 'macos_sdk_env_setup': True}]
[setting MACOSX_DEPLOYMENT_TARGET to 10.15.4]
[setting SDKROOT to /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk]
[spack spec: %clang]
[installing to: /Users/joe/Downloads/ascent/build]
[info: destination '/Users/joe/Downloads/ascent/build' already exists]
[info: cloning spack develop branch from github]
[exe: git clone -b task/2019_11_update_ascent https://github.com/alpine-DAV/spack]
Cloning into 'spack'...
remote: Enumerating objects: 2, done.[K
remote: Counting objects:  50% (1/2)[K
remote: Counting objects: 100% (2/2)[K
remote: Counting objects: 100% (2/2), done.[K
Receiving objects:   0% (1/196436)
Receiving objects:   0% (12/196436), 12.00 KiB | 0 bytes/s
Receiving objects:   0% (26/196436), 20.00 KiB | 0 bytes/s
Receiving objects:   0% (38/196436), 28.00 KiB | 0 bytes/s
Receiving objects:   0% (52/196436), 36.00 KiB | 0 bytes/s
Receiving objects:   0% (66/196436), 44.00 KiB | 0 bytes/s
Receiving objects:   0% (86/196436), 52.00 KiB | 0 bytes/s
Receiving objects:   0% (104/196436), 60.00 KiB | 0 bytes/s
Receiving objects:   0% (117/196436), 68.00 KiB | 0 bytes/s
Receiving objects:   0% (130/196436), 76.00 KiB | 0 bytes/s
Receiving objects:   0% (144/196436), 84.00 KiB | 0 bytes/s
Receiving objects:   0% (156/196436), 92.00 KiB | 0 bytes/s
Receiving objects:   0% (170/196436), 100.00 KiB | 0 bytes/s
Receiving objects:   0% (182/196436), 108.00 KiB | 0 bytes/s
Receiving objects:   0% (195/196436), 116.00 KiB | 0 bytes/s
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
[disabling config scope (except default) in: /Users/joe/Downloads/ascent/build/spack/lib/spack/spack/config.py]
Traceback (most recent call last):
  File "scripts/uberenv/uberenv.py", line 548, in <module>
    sys.exit(main())
  File "scripts/uberenv/uberenv.py", line 448, in main
    patch_spack(dest_spack, uberenv_path, cfg_dir, pkgs)
  File "scripts/uberenv/uberenv.py", line 229, in patch_spack
    disable_spack_config_scopes(spack_dir)
  File "scripts/uberenv/uberenv.py", line 217, in disable_spack_config_scopes
    cfg_script = open(spack_lib_config).read()
FileNotFoundError: [Errno 2] No such file or directory: '/Users/joe/Downloads/ascent/build/spack/lib/spack/spack/config.py'
</code>

Do you have any ideas about the problem? Thanks in advance!

**Comment by mclarsen** [comment]
We use spack to build our dependencies and this means that the git clone of that repository failed. The last error is just a symptom of the failed clone. My suggestion is just try to run the command again.

**Comment by cyrush** [comment]
Yes, it looks like the clone failed and the spack dir doesn't exist. 

We should add check to provide a more useful error message.  I'll do that in the future.

**Comment by JoyboyWang** [comment]
> We use spack to build our dependencies and this means that the git clone of that repository failed. The last error is just a symptom of the failed clone. My suggestion is just try to run the command again.

Alright, I have tried several times but failed. I guess there are some problems with my network, maybe I can copy the *spack* folder from my colleague. Thanks anyway!

**Comment by cyrush** [comment]
closing, since we added an error message for failed clone as part of #620.

Thanks for providing details about this case!
