### ISSUE TITLE
2D multi-domain camera issue

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#592]
4 domain 2D data set, rendering is off with default camera settings. Domains are shifted around in a strange way.
Setting the azimuth to 0.0 `fixes` the issue. (This was noticed by adding camera params to the actions)

Diving in + editing the code, confirmed that setting Azimuth to 0.0 as part of the default rendering path also produces the expected image. 

Looking at the camera details - setting the Azimuth changes the camera mode from 2D to 3D. This points to an issue with the 2D camera.  Consistent bounds + camera settings seem to be passed from Ascent and VTK-h on all ranks, so this might be a VTK-m issue. 

Cyrus has data on LLNL RZ Power9 system.

**Comment by mclarsen** [comment]
Did we fix this?

**Comment by cyrush** [comment]
I believe so
