### ISSUE TITLE
Require newer version of CMake?

### ISSUE THREAD

**Issue by hankchilds** [Alpine-DAV/ascent#610]
I was building on UO's Alaska machine.  If I built everything with Spack, it worked.  That said, it did not leave me a build version that I could modify.
So I tried doing a new checkout and bringing the .cmake file over, using all of the third party libraries that were built by Spack.
My invocation was: "cmake -C alaska.cmake ../src"
This failed, reporting a vague Conduit+Python problem.
After some digging, I tried using a newer CMake.
It _worked_ with the newer CMake.
Specifically, failed with 3.10, worked with 3.14.
I note VTK-m requires 3.14 (which was the hint I needed to figure this out).
The proposed change is that Ascent's adds a requirement to its build that CMake be 3.14 or newer.
Also: I suspect this issue is screwing up attempts to compile on Cori.  Cori's module system claims 3.14 is the default, but they actually have the default as 3.10 as well.  (at least when I log in and say "cmake --version", I get 3.10)

**Comment by cyrush** [comment]
Do you still have the error message about what failed?  Cmake 3.10 in general had issues that undermined a few things. 

Also, at one point, things where ok with cmake 3.9 when you didn't have cuda on - but cuda w/ VTK-m required cmake >= 3.14. We would not recommend cmake 3.10, 3.11, 3.12, or 3.13.

**Comment by hankchilds** [comment]
Looks like you are right to push back.  I am trying to reproduce on both Alaska and Cori and am now getting a different problem (VTK-m errors out, saying it needs 3.12) when I do the steps above.
Options going forward:
(1) close this out.
(2) change Ascent to require 3.14.

I note my students have a lot of issues getting Ascent built, and (to me) it makes sense to put the CMake requirement at 3.14, since that is what you recommend.  But it is OK to close this out too.

**Comment by mclarsen** [comment]
We now have tested cmake 3.18.2 on summit, so I am going to close this.
