### ISSUE TITLE
How to run the project example

### ISSUE THREAD

**Issue by YanlinWangWang** [Alpine-DAV/ascent#713]
I successfully built the project using the uberenv script, but when I ran the example, python notified me that it was missing the necessary package "No module named'conduit'"
How can I set up the environment to solve this problem

**Comment by cyrush** [comment]
@YanlinWangWang  uberenv will build its own python (with all the necessary modules) as part of the process. 

you should be able to run this python with  using the `<path/to/ascent-install>/bin/run_python_with_ascent.sh` helper script.

**Comment by YanlinWangWang** [comment]
thanks for your help！
But I want to know how to run the python file I wrote

**Comment by YanlinWangWang** [comment]
Find it！Thanks
