### ISSUE TITLE
Inject __file__ when running python extract

### ISSUE THREAD

**Issue by gpotter2** [Alpine-DAV/ascent#791]
It would be great if `__file__` was injected in the environment when running a Python script using `add_extracts` and `type: python`. This should be rather easy considering the path to the python file is passed as argument.

Paraview does [that all the time](https://gitlab.kitware.com/paraview/paraview/-/blob/fe9458e77a7e7dee1d0c4892fb1c035a73f97ab0/Qt/Python/pqPythonManager.cxx#L189-L191) for instance.

**Comment by cyrush** [comment]
great suggestion! I'll add this

**Comment by cyrush** [comment]
@gpotter2 I added support for this in PR #792

**Comment by gpotter2** [comment]
Awesome thanks a lot !
