### ISSUE TITLE
better error message when VTK-m is not included

### ISSUE THREAD

**Issue by hankchilds** [Alpine-DAV/ascent#850]
I am building Ascent on my own.  (Uberenv isn't working and I feel I should be able to do this.)
I put VTKM_DIR in my .cmake file, but CMake ignored it and I unwittingly got a version of Ascent with no VTK-m.  This issue is not about my VTKM_DIR being ignored.  That said, I do note that I looked over the result of invoking cmake and there was no mention of VTK-m.  So I could have figured it out if I was looking for VTK-m and noticed its absence, but there was never a moment where it should have been crystal clear I was proceeding without VTK-m.  At this point, I think I have a successful build.

So then I proceed and link to an app.  My ascent_actions.yaml file makes a simple scene.  I then run the simulation code and I get:
[Error] Ascent::execute 
file: /home/users/hank/ghosts/ascent.noopenmp/src/flow/flow_workspace.cpp
line: 456
message: 
Cannot create unknown filter type: default_render

It took me embarrassingly long to figure out the issue was because VTK-m was not compiled in. 

I propose that flow_workspace.cpp has its error message improved to include that VTK-m was not built in these cases.  For example:
Cannot create unknown filter type: default_render.  Your version of Ascent was not compiled against VTK-m, and this filter may be missing since since VTK-m is not present.

**Comment by cyrush** [comment]
thanks @hankchilds, I added a better error message for this case.
