### ISSUE TITLE
ASCENT_INSTALL_PREFIX is ignored unless CMAKE_INSTALL_PREFIX is also set

### ISSUE THREAD

**Issue by hankchilds** [Alpine-DAV/ascent#851]
I am building Ascent without uberenv.  In this case, I want to build a version that I can debug.  I need to install it so I can link a simulation code against my debugged version.

I tried setting ASCENT_INSTALL_PREFIX in cmake, but was unsuccessful.  If I set it as "cmake -DASCENT_INSTALL_PREFIX=..." then whatever I put would be ignored and it would say /usr/local.  Similarly, if I modified CMakeCache.txt to have a different value and then ran "make" (which invokes cmake), then it would reset it to /usr/local/.  

I found that it worked correctly if I also set CMAKE_INSTALL_PREFIX.  I am not sure what is the right "fix" here, but want to document the issue.  This took a long time to figure out how to work around.  Perhaps this is a necessary evil with CMake and the solution is documentation.

**Comment by cyrush** [comment]
@hankchilds `ASCENT_INSTALL_PREFIX`  is actually an output variable - it is used when other cmake build systems import from an installed ascent. 

`CMAKE_INSTALL_PREFIX ` is the standard thing to set. 

Q: Did you discover `ASCENT_INSTALL_PREFIX` via ccmake? I can try to hide it there.  There are probably other vars that could use the same treatment.

**Comment by cyrush** [comment]
i ask about ccmake, b/c the same confusion occurred with conduit:

https://github.com/LLNL/conduit/blob/c5babc8c434a7dc22e8c397797f3b99e075792f2/src/libs/conduit/CMakeLists.txt#L17


I'll go ahead and apply the same solution.

Sorry this was confusing!

**Comment by cyrush** [comment]
I added the fix in: https://github.com/Alpine-DAV/ascent/pull/852
