### ISSUE TITLE
Update ascent spack package to add "+testing" to vtk-m spec for vtk-m 1.7.0.

### ISSUE THREAD

**Issue by brugger1** [Alpine-DAV/ascent#857]
The new vtk-m 1.7.0 spack install no longer includes the testing header files. In particular, `vtkm/cont/testing/MakeTestDataSet.h`, which is used by some of the ascent tests.

I have a pull request for spack https://github.com/spack/spack/pull/28324, that adds a `testing` variant, that will add the testing files back into an install. When that change is accepted, the ascent spack package should be updated to add "+testing" to the vtk-m spec.

**Comment by cyrush** [comment]
We refactored so Ascent develop no longer depends on `vtk-m+testing`.
