### ISSUE TITLE
Need to include <limits> in halo_compare.cpp

### ISSUE THREAD

**Issue by kwryankrattiger** [Alpine-DAV/ascent#860]
Trouble building on Spock with gcc@11.2.0. It seems this is no longer included via the other STL headers included in this file.

**Comment by cyrush** [comment]
thanks @kwryankrattiger -- was this with spack?

I think this issue is resolved in Ascent's `develop` branch, we are planning for a `0.8.0` later this month.  Building `develop` requires several other dependency updates that aren't yet in spack yet.

**Comment by kwryankrattiger** [comment]
Awesome! Would it be possible to backport this in spack? After disabling python and fortran I was able to get this to build, this was just the last thing that wasn't working...that I know of.

**Comment by cyrush** [comment]
resolved in develop and with patch in spack
