### ISSUE TITLE
Conduit version

### ISSUE THREAD

**Issue by mclarsen** [Alpine-DAV/ascent#87]
@cyrush 

#68 added `join_path` into the utils code, but this call exists as `join_file_path` in conduit v0.3.0. How are the spack builds succeeding? Are they using conduit master (which is what I had to do to get it to build)? Maybe I just need to update the build documentation with the correct conduit version.

**Comment by cyrush** [comment]
we do need conduit master & the spack packages are using master, sorry I didn't update the docs to match

**Comment by mclarsen** [comment]
Ok. I'll update the docs.
