### ISSUE TITLE
'invalid device function' error when rendering scene

### ISSUE THREAD

**Issue by BenWibking** [Alpine-DAV/ascent#894]
When creating a simple scene from an AMReX mesh:

```
    conduit::Node blueprintMesh;
    amrex::MultiLevelToBlueprint(finest_level + 1, mf_ptr, varnames, Geom(),
		tNew_[0], istep, refRatio(), blueprintMesh);

    // add a scene with a pseudocolor plot
    Node scenes;
    scenes["s1/plots/p1/type"] = "pseudocolor";
    scenes["s1/plots/p1/field"] = "gasDensity";
    // Set the output file name (ascent will add ".png")
    scenes["s1/image_prefix"] = "ascent_render_" + plotfilename;

    // setup actions
    Node actions;
    Node &add_act = actions.append();
    add_act["action"] = "add_scenes";
    add_act["scenes"] = scenes;
    actions.append()["action"] = "execute";
    actions.append()["action"] = "reset";

    Ascent ascent;
    conduit::Node ascent_options;
    ascent_options["mpi_comm"] = MPI_Comm_c2f(amrex::ParallelContext::CommunicatorSub());
    ascent_options["runtime/type"] = "ascent";

    ascent.open(ascent_options);
    ascent.publish(blueprintMesh);
    ascent.execute(actions);
    ascent.close();
```

I get an invalid device function error from within VTK-m:

```
added new ghost field because of nestset: topo_ghosts2022-03-12 09:22:00.956 (  15.968s) [main thread     ]RuntimeDeviceInformatio:232   WARN| Initializing 'RuntimeDeviceConfigurations' with uninitialized configOptions. Did you call vtkm::cont::Initialize?
2022-03-12 09:22:01.036 (  16.049s) [main thread     ]         TryExecute.cxx:60     ERR| TryExecute encountered an error: after reduction step 1: cudaErrorInvalidDeviceFunction: invalid device function
2022-03-12 09:22:01.037 (  16.049s) [main thread     ]         TryExecute.cxx:60     ERR| Failing functor: vtkm::cont::detail::ReduceFunctor<vtkm::Vec<int, 2> >
2022-03-12 09:22:01.037 (  16.049s) [main thread     ]         TryExecute.cxx:60     ERR| Failing device: Cuda
[Error] Ascent::execute 
file: /avatar/bwibking/ascent/src/ascent/runtimes/ascent_main_runtime.cpp
line: 1746
message: 
Execution failed with vtkm: after reduction step 1: cudaErrorInvalidDeviceFunction: invalid device function
15            0x43854e ../build/src/ShockCloud/shock_cloud() [0x43854e]
14      0x7efc0255f493 __libc_start_main + 243
13            0x433ed5 ../build/src/ShockCloud/shock_cloud() [0x433ed5]
12            0x47e7e9 ../build/src/ShockCloud/shock_cloud() [0x47e7e9]
11            0x47dfc8 ../build/src/ShockCloud/shock_cloud() [0x47dfc8]
10            0x479e78 ../build/src/ShockCloud/shock_cloud() [0x479e78]
9             0x462fc9 ../build/src/ShockCloud/shock_cloud() [0x462fc9]
8       0x7efc133776c6 ascent::Ascent::execute(conduit::Node const&) + 262
7       0x7efc133841a2 ascent::AscentRuntime::Execute(conduit::Node const&) + 978
6       0x7efc130ca537 flow::Workspace::execute() + 807
5       0x7efc134b15b7 ascent::runtime::filters::VTKHGhostStripper::execute() + 599
4       0x7efc11634b83 vtkh::Filter::Update() + 19
3       0x7efc116b0108 vtkh::GhostStripper::DoExecute() + 584
2       0x7efc116afc8d vtkh::detail::StructuredStrip(vtkm::cont::DataSet&, vtkm::cont::Field&, int, int, vtkm::Vec<int, 3>&, vtkm::Vec<int, 3>&, bool&) + 813
1       0x7efc116af862 bool vtkh::detail::CanStrip<3>(vtkm::cont::Field&, int, int, vtkm::Vec<int, 3>&, vtkm::Vec<int, 3>&, vtkm::Vec<int, 3>, int, bool&) + 3954
0       0x7efc115c7ba0 /avatar/bwibking/ascent/install/lib/librover_mpi.so(+0x3b3ba0) [0x7efc115c7ba0]

```

Is this a VTK-m bug, a compiler bug, a possible build problem, or something else?

Thanks,
Ben

**Comment by BenWibking** [comment]
This is built with CUDA 11.5, and running on a V100 GPU.

**Comment by cyrush** [comment]
@BenWibking it could be a few issues. Can you share how you built Ascent and how you are linking into your AMReX code?

**Comment by BenWibking** [comment]
I couldn't get the Spack build to work with +cuda~shared, so I built VTK-m, VTK-h, Conduit, and Ascent manually. I built VTK-m with the options listed here: https://github.com/Alpine-DAV/vtk-h and the specified commit (d5143ad7ed2e55025cec2f49fb3f0ab46045a8e2). I didn't use a host config file, though I see now that is recommended in the docs. If that's the likely culprit, I'll go ahead and rebuild with a host config file.

**Comment by BenWibking** [comment]
I set AMReX_ASCENT=ON and AMReX_CONDUIT=ON as specified [in the AMReX docs](https://amrex-codes.github.io/amrex/docs_html/BuildingAMReX.html#customization-options). I'm not immediately sure whether this tries to link the shared libraries or static libraries.

**Comment by cyrush** [comment]
@BenWibking  

Thanks for the details, here are some suggestions:

I would make sure to build everything static. 

static was required for vtk-m to link in the past.
It shouldn't be an issue with new vtk-m, however we have not tested shared + cuda with the new vtk-m release yet. 

Here are some extra VTK-m build flags that you will need:

`-DVTKm_USE_DEFAULT_TYPES_FOR_ASCENT:BOOL=ON`
`-DVTKm_CUDA_Architecture=volta`
`-DVTKm_NO_DEPRECATED_VIRTUAL:BOOL=ON`

(If you want to share your full vtk-m flags, I am happy to look at them)


We are also using:  vtk-m release 1.7.1 

Commit:
`bac7559926b328199323bb314a6dffc5d93fbe52`


Sorry the hashes and the config details are off. 
Our spack fork is our standard vetted focal point for building and deploying, and I overlooked some other places this is documented and they became stale. 

I will update the hashes and the vtk-h readme.

**Comment by BenWibking** [comment]
Ok, I got it working with the following build settings. However, I had to remove `vtkmdiympi_nompi` from ascent/CMakeLists.txt to get Ascent to build. This doesn't seem to cause any problems, but I'm wondering if it's a symptom of something else that's gone wrong?

*Building Conduit: (latest develop commit)*

cmake ../src -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DENABLE_MPI=ON -G Ninja -DCMAKE_INSTALL_PREFIX=../install

*Building VTK-m: (commit* `bac7559926b328199323bb314a6dffc5d93fbe52`)

cmake .. -DVTKm_USE_DEFAULT_TYPES_FOR_ASCENT:BOOL=ON -DVTKm_CUDA_Architecture=volta -DVTKm_NO_DEPRECATED_VIRTUAL:BOOL=ON -DVTKm_USE_64BIT_IDS:BOOL=OFF -DVTKm_USE_DOUBLE_PRECISION:BOOL=ON -DCMAKE_INSTALL_PREFIX=../install -G Ninja -DCMAKE_BUILD_TYPE=Release -DVTKm_ENABLE_CUDA=ON -DVTKm_ENABLE_MPI=ON -DBUILD_SHARED_LIBS=OFF

*Building VTK-h: (commit* `76c9a1c9be0c30ef4b73cdd5ae0820bb4408b853`)

cmake ../src -DENABLE_CUDA=ON -DENABLE_MPI=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install -DBUILD_SHARED_LIBS=OFF -G Ninja -DVTKM_DIR=../../vtk-m/install

*Building Ascent: (latest develop commit)*

cmake ../src -DBUILD_SHARED_LIBS=OFF -DENABLE_FORTRAN=OFF -DENABLE_PYTHON=OFF -DENABLE_MPI=ON -DENABLE_CUDA=ON -DENABLE_EXAMPLES=OFF -DENABLE_DOCS=OFF -DCMAKE_BUILD_TYPE=Release -G Ninja -DCONDUIT_DIR=../../conduit/install -DVTKH_DIR=../../vtk-h/install -DVTKM_DIR=../../vtk-m/install -DCMAKE_INSTALL_PREFIX=../install

**Comment by cyrush** [comment]
Thanks for the extra info -- yes, this is an issue with `-DVTKm_ENABLE_MPI=ON`,  (lib name changes based on this setting) there is a possible fix for this in this PR:

https://github.com/Alpine-DAV/ascent/pull/903/

**Comment by BenWibking** [comment]
Thanks, will take a look.
