### ISSUE TITLE
log_10 filter in addition to log filter

### ISSUE THREAD

**Issue by BenWibking** [Alpine-DAV/ascent#906]
It looks like the log filter applies the natural logarithm, rather than log base 10. This was a bit surprising, since VisIt applies log10 when logarithmic scaling is selected. I can work around this by applying a scale filter, but a native log10 filter would be very convenient for new users, and would reduce the possibility of confusion.

Edit: looks like the scale filter scales the box, rather than the data. A log10 filter would be very useful.

**Comment by cyrush** [comment]
sure thing -- we can add a log10 filter.

**Comment by nicolemarsaglia** [comment]
Great suggestion. This is being added with PR #961 

type is now "log10"
