### ISSUE TITLE
SetupADIOS2 issues

### ISSUE THREAD

**Issue by kwryankrattiger** [Alpine-DAV/ascent#916]
Currently Ascent is using the variable `<PACKAGE>_DIR` to explicitly find the config files for third-party libraries. The problem with this is `find_package` sets the `<Package>_DIR` after a find package. This currently doesn't cause issues because many packages, like `Conduit`, have the ascent version of the var `CONDUIT_DIR` and the `find_package` version of the var is `Conduit_DIR`.

However, in the case of `ADIOS2` both ascent and find_package use the `ADIOS2_DIR`. What this means is packages like sensei depend on both ascent and adios2 there is a collision.

A solution for this is to use the `<Package>_ROOT` variable instead since the sole purpose of this variable is to be the prefix path to the package's installation. Another option is to check if `lib/cmake/adios2` is already appended to the `ADIOS2_DIR` and conditionally append it in the `find_package` call.

Note: The solution work around in sensei was to re-order configuring the packages. This is not stable because it will always fail to re-configure unless the `ADIOS2_DIR` is manually removed from the `CMakeCache.txt` or the variable is specified in each configure. I would imagine this would also cause issues in a re-configure of ascent with ADIOS2 support as well.

@cyrush

**Comment by cyrush** [comment]
we can shift to use `ZZZ_ROOT`, since that is spirit of how we use `ZZZ_DIR` s
