### ISSUE TITLE
multi-arch build support for Spack builds?

### ISSUE THREAD

**Issue by BenWibking** [Alpine-DAV/ascent#950]
Hi,

I've build Ascent with `spack install ascent@develop+cuda+vtkh~fortran cuda_arch=70,80 ^conduit~parmetis~fortran` using the upstream Spack.

I've built my AMReX code as a multi-arch CUDA binary and linked it to this Ascent build. Everything works as expected on Volta, but when running on A100, I get no output from Ascent (the simulation runs fine, though).

Is doing a multi-`cuda_arch`-build supported? Or should I just build Ascent separately for Volta and Ampere?

**Comment by cyrush** [comment]
Quick answer - you will need to build separate versions.

The VTK-m spack package translates spack cuda arch values into it's own list of names. 

https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/vtk-m/package.py#L116

https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/vtk-m/package.py#L195


VTK-m does have a new feature to use the arch directly, but its not in spack yet and  I am not sure if supports multiple values in the internal CMake logic.

We can make this work in the future, but will take a bit to sort out.

**Comment by BenWibking** [comment]
We've switched to the bash scripts to build Ascent, rather than using Spack, so I'll close this.
