### ISSUE TITLE
include of vtkm/cont/testing/Testing.h

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#953]
@nicolemarsaglia pretty sure this is on your radar -- wanted to create a ticket to track:

There is one include still for the vtk-m testing lib.

https://github.com/Alpine-DAV/ascent/blob/e6de535d9f54f0a51a8d862143b41d93ac24a528/src/tests/vtkh/t_vtkm_test_utils.hpp#L11

I hit this when testing container updates that don't have a build vtk-m w/ the testing lib

**Comment by nicolemarsaglia** [comment]
Thanks! Working on a fix in #954

**Comment by cyrush** [comment]
resolved in #954
