### ISSUE TITLE
Unknown CMake command "vtkm_add_target_information".

### ISSUE THREAD

**Issue by WillTrojak** [Alpine-DAV/ascent#986]
I'm trying to compile Ascent with vtkh rendering support, and I get the following error when running cmake. 

```
...
-- CONDUIT_INCLUDE_DIRS = /Users/wtrojak/Documents/code/pyfr_venv/include/conduit;/Users/wtrojak/Documents/code/pyfr_venv/python-modules//conduit
-- Tests are enabled (ENABLE_TESTS=ON)
CMake Error at libs/vtkh/utils/CMakeLists.txt:36 (vtkm_add_target_information):
  Unknown CMake command "vtkm_add_target_information".
```

This is the cmake command I'm running:
```
cmake -DENABLE_VTKH=true -DVTKH_ENABLE_FILTER_CONTOUR_TREE=true -DCONDUIT_DIR="/Users/wtrojak/Documents/code/pyfr_venv/" -DPYTHON_EXECUTABLE:FILEPATH="/Users/wtrojak/Documents/code/pyfr_venv/bin/python3.10" -DENABLE_PYTHON=true -DENABLE_FORTRAN=false -DENABLE_MPI=true -DCMAKE_INSTALL_PREFIX:PATH=/Users/wtrojak/Documents/code/pyfr_venv/ ../src/.
```

This is with Cmake v3.24.0, Ascent commit 6a42e5f99dd6fe07516b55bb0668972f31cdc100, and vtk-m v1.8.0.

Any help you can offer would be great.

**Comment by WillTrojak** [comment]
Sorry obivious answer, the following has to be set when calling cmake `-DVTKM_DIR="..."`

**Comment by cyrush** [comment]
No worries!

Just in case you haven't seen it yet -- we now have a full example of building third party libs and Ascent in our docs. It's a good reference, but also a script that we test with our CI and you can try to run as well.

https://ascent.readthedocs.io/en/latest/BuildingAscent.html#building-ascent-dependencies-manually
