### ISSUE TITLE
Rendering issue with MPI

### ISSUE THREAD

**Issue by WillTrojak** [Alpine-DAV/ascent#992]
I have been experiementing with integrating Ascent in PyFR, and have come across an issue when rendering feilds when the domain is distributed across partitions. 

What I found is that for domains $[-a,a]^2$, subdivived into elements, when paritioned into 2 or more parts. If $a
\leq\sim3.6$ then the image doesn't render correctly. For exmpale for 2 parts, half of the elements from each partition get dropped.

I wrote a simple example using the C API, for a 4 element quad mesh with 2 parts. See the code below. The results for setting a=4 are shown in the attached figure. 

![test_scene_mesh](https://user-images.githubusercontent.com/30172689/185958307-db67c2a9-cb88-44c4-956c-a6ab297a0fb0.png)
![test_scene_u](https://user-images.githubusercontent.com/30172689/185958310-8ddbc5cc-e681-4a8f-8a67-2969823a1395.png)

[ascent_part_test.c.zip](https://github.com/Alpine-DAV/ascent/files/9395608/ascent_part_test.c.zip)

I am seeing this behaviour an both a Linux x86 system with GCC 12.2 as well as a ARM M1 Pro system with clang 13.1.6. 
In both cases I am using Ascent commit bbfc9a89780a3209b704fd4a8c4805c88d1dbe8d and Conduit commit 04b603c51f7ddd33504853678b1bc0601e2db15d, with rendering from VTK-m 1.8.0.

**Comment by cyrush** [comment]
@WillTrojak confirming I see the same issue. I exported the data and looked at it in VisIt and it looks as I expect:

![Screen Shot 2022-08-31 at 11 56 28 AM](https://user-images.githubusercontent.com/1194526/187760407-901552d0-bc6b-4b53-866a-5d51ac3b9e4a.png)

Here is an hdf5 version of this dataset:
[tout_example.tar.gz](https://github.com/Alpine-DAV/ascent/files/9464295/tout_example.tar.gz)


So there is an issue with Ascent -- We will look into it.

**Comment by WillTrojak** [comment]
@cyrush , thanks for looking into this.

**Comment by WillTrojak** [comment]
I was wondering if there was any update on the source of this bug?

**Comment by nicolemarsaglia** [comment]
@WillTrojak I am close to finding the problem, but not yet, unfortunately. I plan on spending more time on it today. This bug has been nontrivial, to say the least.

**Comment by nicolemarsaglia** [comment]
I found the issue. VTK-m was passing Ascent negative depths values (not just for background), which Ascent is not equipped to handle. 

PR #1024 is addressing the issue.

**Comment by WillTrojak** [comment]
Excellent, thanks for your work on this bug! I'll test it later this afternoon and if it works, I'll close this issue.

**Comment by nicolemarsaglia** [comment]
Sounds good! My fix did end up breaking some test cases so I'm going to fiddle with the implementation.

**Comment by nicolemarsaglia** [comment]
New implementation works and is passing all CI testing.

**Comment by WillTrojak** [comment]
Sorry I only just got around to testing this in PyFR. Yes this works for me, thanks for sorting this.

**Comment by cyrush** [comment]
@WillTrojak thanks for confirming!
